### ISSUE TITLE
Request integration with org-id for link support

### ISSUE THREAD

**Issue by mengwong** [org2blog/org2blog#104]
thank you for org2blog. I am enjoying it.

I am using org-id with '(org-id-link-to-org-use-id (quote create-if-interactive))

I link from one org heading to another using the PROPERTIES ID.

It would be nice if org2blog could intelligently translate private ID links into the appropriate public-facing URLs, so that links will work seamlessly: entries that link to one another would become blog posts that link to one another, either using the POSTID or the PERMALINK.

Support for other forms of Org links could also be useful, like file links.

I notice that Org2blog also uses the ID property with an o2b prefix.

I would be willing to pay for this feature.

**Comment by kozikow** [comment]
I am not entirely sure if this is what you were asking about, but I think you meant making links exported by org mode globally unique.
I made a simple hack that works for me: https://kozikow.wordpress.com/2016/06/05/make-internal-links-exported-by-org-unique/ .

**Comment by grettke** [comment]
@mengwong There are a few different ways to think about this. So I need to know how you are thinking about it compared to what I have imagined. Here is what I am thinking as a most simple as humanly possible scenario:

Say you have a blog. Each Org2Blog entry is written in a file. There is one entry per file. These are not subtree entries. Every entry has already been posted: so each one already has a `#POST_ID`.

All entries are located in the same directory. When you open your entry and want to link to another entry you use the normal link behavior. For example there are two files in a directory `entry1.org` and `entry2.org`. To create a link in `entry1.org` to `entry2.org` you write:

    [[file:entry2.org][test link to entry 2]]

This is a normal link. Inside of Emacs you can select it and jump to that file. Now the behavior has to get special when Org2Blog publishes `entry1.org`. It might look something like this:

When you publish an entry Org2Blog looks at all of the links inyour entry. For each one it finds it determines his:

- Is it a link to a local file?
- Yes. Is it an Org file?
- Yes. Is it an Org2Blog file (it has an `#ORG2BLOG` file property)?
- Yes. Does it have a `#POST_ID` property?
- Yes: 12858. So therefore when its generates a URL it will link to the to the post ID on the blog like this

    https://www.wisdomandwonder.com/?page_id=12858

What do you think?

**Comment by grettke** [comment]
Closing this issue because it is not active and it isn't obvious how to move forward with it. If work can start again then this task will get get re-opened.
