### ISSUE TITLE
XML-RPC fault: Could not write ... Invalid file type

### ISSUE THREAD

**Issue by mengwong** [org2blog/org2blog#105]
I tried to do a M-x org2blog/wp-post-subtree and got:

let: XML-RPC fault `Could not write file wpid-outline.htmlID-FDEDC9CF-EEF0-4E2D-846D-92FA799F82A2 (Invalid file type)'

is an ID being appended by mistake to the filename somewhere?

I tried to identify the relevant code in the org2blog.el source but my lisp isn't good enough.

**Comment by thiagowfx** [comment]
This happened to me when I tried to submit a post with a local link, e.g.

`[[../link/to/parent/directory][label]]`

Just remove links of this type and everything will work fine.
