### ISSUE TITLE
'>' is converted to '&gt;'

### ISSUE THREAD

**Issue by redguardtoo** [org2blog/org2blog#129]
```
#+begin_src sh
echo hello > world
#+end_src
```

is converted to

```
<code>
echo hello &gt; world
</code>
```

in my .emacs:

``` lisp
(setq org2blog/wp-use-sourcecode-shortcode t)

```

check an example: http://blog.binchen.org/?p=742

**Comment by timmolter** [comment]
I'm experiencing this issue with the latest version. I paste code containing `<` and `>` and when Crayon injects it into my Wordpress post, it converts it to `&lt;` and `&gt;`. Any ideas?

**Comment by Asher256** [comment]
+1 

I experienced the same issue

**Comment by ernest-dzf** [comment]
Why don't you want html escape the src code?
I just want to html escape the src code, and it seems that org2blog/wp does not html escape the code!

**Comment by mark-me** [comment]
This is driving me nuts. Has anyone found a fix for this yet? The [pre] stuff seems the screw up my whole page. I must be doing something wrong, but I have no idea what. I'm hoping there is a fix, because I'm not looking forward to migrating.

**Comment by grettke** [comment]
@mark-me Can you help me understand what you did, what you wanted to have as a result and the actual result you got instead?

**Comment by mark-me** [comment]
Thank you for your quick reply! I've put this R code into a 'Preformatted' section:
[code gutter="false" language="r"]sentiment_order <- c("fear", "trust", "joy", "anticipation", "anger", "disgust", "sadness", "surprise")
degrees_sentiment <- c(0, 45, 90, 135, 180, 225, 270, 315)
tbl_sentiments <- data.frame(sentiment_order, degrees_sentiment)[/code]

After I've saved it (probably I've saved it a few times seeing the repetitions of the amp;).:
[code gutter="false" language="r"]sentiment_order &amp;amp;amp;amp;amp;lt;- c("fear", "trust", "joy", "anticipation", "anger", "disgust", "sadness", "surprise")
degrees_sentiment &amp;amp;amp;amp;amp;lt;- c(0, 45, 90, 135, 180, 225, 270, 315)
tbl_sentiments &amp;amp;amp;amp;amp;lt;- data.frame(sentiment_order, degrees_sentiment)[/code]

**Comment by grettke** [comment]
Am I seeing this right, that `<-` should not translate to `&amp;amp;amp;amp;amp;lt;-`, but rather that it should translate to `lt;-`?

**Comment by mark-me** [comment]
Well... I'm not too sure how to answer this (I'm not what you call a WordPress expert). What I want to show at the end user is a <-.  I can live with typing a lt;- in the editor to achieve that, but I just tested that and it doesn't.

**Comment by mark-me** [comment]
![image](https://user-images.githubusercontent.com/12082379/28909436-c7b4f46e-7828-11e7-8e1e-c2be65f97ed5.png)
is the result of that test in preview mode.

**Comment by grettke** [comment]
Gotcha. Some WordPress features are new to me, too. Can you post the Org-Mode code that you are using? Attaching the file is fine.

**Comment by mark-me** [comment]
I'm such a newbie that I don't know what a Org-Mode is. I'm just using the standard WordPress editor.

**Comment by grettke** [comment]
That is totally fine. Whatever you are facing will probably get resolved soon. Have a great rest of your day.

**Comment by mark-me** [comment]
Thanks for understanding and quick replies! Have a great day too!

**Comment by cpbotha** [comment]
@mark-me Hmm, I often do this type of stuff. Not with R, but with emacs-lisp and Python.

I have found that using native Emacs syntax highlighting with the htmlize package (vs the wordpress syntax highlighter plugin) gives me the best results. See any of the recent posts on https://vxlabs.com/

Ensure that package `htmlize` is installed, and add this to your emacs config (it's a commented excerpt from mine):

``` emacs-lisp
        ;; without wp-use-sourcecode-shortcode 't, org2blog won't use the
        ;; syntaxhighlighter source code. Well, if you keep this to nil,
        ;; native emacs highlighting will be used, which is often prettier.
        (setq org2blog/wp-use-sourcecode-shortcode nil)
```

**Comment by seyoum** [comment]
This is still an issue for me. And this issue is originally from 2013 😨 ?
I am using jetpack markdown, but I don't think that should matter.

**Comment by grettke** [comment]
@seyoum I hear you, that must be pretty frustrating. Here in the process of Emacs to Org-Mode to WordPress does JetPack Markdown fit into your workflow here?
