### ISSUE TITLE
suggestions on track-posts

### ISSUE THREAD

**Issue by shelper** [org2blog/org2blog#130]
currently the org2blog tracks the posts in .org2blog.org only when i save the post locally, I think it would be better to track the post whenever i publish to my blog but without saving a local copy

in addition, in case i want to revisit and modify a post, it would be great if i can open the .org2blog.org file, find the headline of the post, and run some org2blog function to retrieve the content of the post from the remote blog site, and open it as an org file in a new buffer. 

or maybe i missed the function already available, please let me know if so, (or put into the readme :)
thanks!

**Comment by QingQYang** [comment]
Is there any solution to this feature? Or is there any method to set the location of .org2blog.org file?

**Comment by punchagan** [comment]
See `org2blog/wp-track-posts` variable.

**Comment by grettke** [comment]
[This script](https://github.com/punchagan/org2blog-importers/blob/master/wp_to_org2blog.py) exports an entire WP database to Org2Blog files. If you are doing it for one file you could pull some parts out, or you could just re-create the post manually.

- Create a brand new post just to get the post body laid out. Use `org2blog/wp-new-entry`.
- Get the correct post id and date and insert it like this
    #+POSTID: 8
    #+DATE: [2007-12-14 Fri 03:02]
- Manually convert the existing post from HTML into Org-Mode. Install . Copy the HTML from the rendered blog post and place it in a file. Then run Pandoc with something like this `pandoc -r html -t org --no-wrap`. Put that in the body of this new file.
