### ISSUE TITLE
make the image link support lightbox 

### ISSUE THREAD

**Issue by redguardtoo** [org2blog/org2blog#132]
see http://wordpress.org/plugins/lightbox-plus/

the point is adding "rel" attribute for image link.

maybe it's not org2blog issue but org issue.

Do you know how to do it?

**Comment by grettke** [comment]
Seems like a neat feature https://themeisle.com/blog/wordpress-lightbox-plugins/ .

The first step is to make it work in plain old Org-Mode HTML export, so marking it as closed.
