### ISSUE TITLE
Image Upload

### ISSUE THREAD

**Issue by stevenarntson** [org2blog/org2blog#147]
I'm new to org2blog and github.
versions: emacs 24.3.1, org 8.2.5h, org2blog 20130707.323

When I insert a path to an image in my buffer, such as file://~/doc/file.png or [[./doc/file.jpg]] the image seems to upload okay with the rest of the text (Mx org2blog/wp-post-buffer-as-page), but then Wordpress won't display it. When I click on the edit link on the image's details page in the media library, it says "Image data does not exist." I have successfully used these same files by uploading them with the wordpress browser form.

Thank you! I am very much enjoying using org2blog so far.
-steven

**Comment by theflysurfer** [comment]
Hello
This is my first day with org2blog (and around 1 month in emacs). I am really glad to be able to pusblish to wordpress, however, I am having the same issue : the image is referenced in the export, and in the worpdress post, but it is uploaded as a 0k file on the ftp server.

![Emacs buffer](http://bit.ly/2Lc5FQS)

![Filezilla screenshot](http://bit.ly/2LcojI7)

![Wordpress post](http://bit.ly/2LcZVpR)

What kind of information could I provide to you for you to be able to help ?
Thanks in advance
