### ISSUE TITLE
Breaking format change in WP 3.9

### ISSUE THREAD

**Issue by grettke** [org2blog/org2blog#160]
Good evening,

Tonight I tried to get org2blog-wp working and ran into an issue… namely it
didn't work. Here is I suspect why. First, library details:

```
(format "%S\n%S" (emacs-version) (org-version))
```
# +RESULTS:

: "GNU Emacs 24.3.1 (x86_64-apple-darwin13.2.0, Carbon Version 1.6.0 AppKit 1265.2)
:  of 2014-06-15 on orion"
: "8.2.7a"

The latest releases were grabbed from MELPA for:
-   org2blog
-   xml-rpc
-   metaweblog

They are all loaded with `require` statements.

Second, WordPress is at version 3.9.1.

Third, I wanted to make sure that my site was working correctly so I did some
basic testing to see if the URL was up:

```
curl http://www.wisdomandwonder.com/wordpress/xmlrpc.php
```

and it was OK.

Then I looked at the WP API for how to load a post
so I built a message like this via :

It looks like this:

```
<?xml version="1.0" encoding="iso-8859-1"?>
<methodCall>
  <methodName>wp.getPost</methodName>
  <params>
   <param><value>1</value></param>
   <param><value>admin</value></param>
   <param><value>*****</value></param>
   <param><value>8779</value></param>
  </params>
</methodCall>
```

Run it like this:

```
curl --data @wnwPost.txt http://www.wisdomandwonder.com/wordpress/xmlrpc.php
```

And it worked giving the results as you would expect.

With that I know that:
-   Service is up
-   Credentials are OK
-   Data exists

Then I tried using the API like this:

```
(setq xml-rpc-debug 5)
(xml-rpc-method-call
 "http://www.wisdomandwonder.com/wordpress/xmlrpc.php"
 'wp.getPost
 1 "admin" "*****" 8779)
```

That did not work, got a 400 error for bad request. Wanting to see the
difference I made the call again like this:

```
(setq url-debug 5)
```

And it showed the actual request:

```
<?xml version="1.0" encoding="UTF-8"?>
<methodCall>
  <methodName>wp.getPost</methodName>
  <params>
    <param>
      <value>
        <int>1</int>
      </value>
    </param>
    <param>
      <value>
        <string>admin</string>
      </value>
    </param>
    <param>
      <value>
        <string>*****</string>
      </value>
    </param>
    <param>
      <value>
        <int>8779</int>
      </value>
    </param>
  </params>
</methodCall>
```

A diff picture is attached: 
![thedifference copy](https://cloud.githubusercontent.com/assets/2521647/3394685/fc9b8e8c-fce7-11e3-968b-6f5b6e46be6e.png)

The difference is that when the parameter types are not indicated, the call
works fine and when they are indicated then the call does not work.

Also, the former uses an ISO encoding that I did not look up, but the latter uses UTF-8, and I am wondering if UTF-8 would matter.

Questions:
-   What do you think?
-   How may I go about using org2blog in a way that does not wrap the
  parameters with their types?

Kind regards,

gcr

<div id="footnotes">
<h2 class="footnotes">Footnotes: </h2>
<div id="text-footnotes">

<div class="footdef"><sup><a id="fn.1" name="fn.1" class="footnum" href="#fnr.1">1</a></sup> <p><http://codex.wordpress.org/XML-RPC_WordPress_API/Posts></p></div>

<div class="footdef"><sup><a id="fn.2" name="fn.2" class="footnum" href="#fnr.2">2</a></sup> <p><http://www.ethicalhack3r.co.uk/introduction-to-the-wordpress-xml-rpc-api/></p></div>

</div>

</div>

**Comment by grettke** [comment]
Today I revisited this. I could not reproduce it.

**Comment by grettke** [comment]
Now I can reproduce it.

**Comment by manuel-uberti** [comment]
I know this is not helpful, but with latest org2blog from MELPA and Emacs `25.0.50.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.18.2) of 2015-10-15` everything is working fine.

**Comment by grettke** [comment]
@manuel-uberti That /is/ helpful. Thank you! I must figure out if there is an issue and the host or somehow on my box, because the API is *not* changing in org2blog, metaweblog, or xml-rpc.

**Comment by manuel-uberti** [comment]
Could you give it a try with `emacs -Q`?

**Comment by grettke** [comment]
Good idea. I need to debug this the right way.

**Comment by grettke** [comment]
Good evening,

[Here](https://github.com/grettke/help/blob/master/.org-mode-org2blog.emacs.el) is my minimal-configuration file that only:

-   Configures load behavior
-   Configures the package system
-   Loads and Org-Mode and Org2blog from source

Tonight I tested it out; revisiting this topic. The goal was to find out if
other packages were causing a problem.

When I try to log in via `org2blog/wp-login` I get a 400 error. When I set up
debugging, take the generated XML, and make the request with cUrl, I don&rsquo;t get
the 400 error.

Because org2blog is working for everyone else, I&rsquo;m starting to wonder if the
issue with my web host. The reason is that things worked fine, stopped working
for a week, and then started working again, and now finally do not work.

I feel like I&rsquo;ve looked at everything else, but I&rsquo;ve stared at it for so long
I&rsquo;m not sure I see the forest for the trees at this point.

**Comment by yanivdll** [comment]
Hi @grettke, wonder if you were able to figure our what was the issue with your hosting. I'm running into similar issues with posting to wp using org2blog.

Initially, I posted to my blog on wordpress.com. Everything worked fine. I then planned to moved bluehost. I tried to post to my temporary url, but got the same 400 error. I tested on my localhost wp, and everything worked fine. 

After completing the migration to bluest, and changing the url, I tried org2blog again, and still nada. I suspect that there's something in my host that causing the problem. 

Thanks.

**Comment by yanivdll** [comment]
ok, turned out it /was/ a problem with my host (bluehost) - my ip was blocked from accessing xmlrpc.php. My IP was whitelisted and now it work**. 

** Though support couldn't promise that other IPs won't be blocked as well...

**Comment by grettke** [comment]
@yanivdll Thanks for sharing that. I still haven't got a reply from them. I'm considering switching to DigitalOcean.

**Comment by grettke** [comment]
It was problem with my host. I switched to a new one and it worked just fine.
