### ISSUE TITLE
xml-rpc error: 'no responseMethod found'

### ISSUE THREAD

**Issue by wohfab** [org2blog/org2blog#180]
I got the **no responseMethod found** error while using _C-u M-x org2blog/wp-post-subtree_ to publish a subtree to my blog.

After half an hour I found the problem:

I had **+** and **=** signs within the subtree heading.
After removing them, I can publish again.

```
emacs 24.3.50.1 (x86_64-pc-linux-gnu, GTK+ Version 3.10.6)
Org-mode 8.2.10 (8.2.10-30-gca21b7-elpa)
```
## EDIT 01

Okay actually it happened again; no special characters in the heading now..
## EDIT 02

I traced it back to **links**. When I delete all the links in my post, it happens to be fine..

Any of those will be posted/published as usual:

```
http://
http://www
http://www.
http://www.test
http://www.test.
```

But as soon as there is something behing this..

```
http://www.test.com
```

It fails..
## EDIT 03

The HTML request buffer from:

```
M-: (setq xml-rpc-debug 2) RET
```

gives me [THIS (pastebin)](http://pastebin.com/nVVAeqGw)
## EDIT 04

Maybe I am doing something wrong? ( https://asciinema.org/a/16389 )

**Comment by wohfab** [comment]
Okay actually it happened again; no special characters in the heading now..

**Comment by wohfab** [comment]
I traced it back to links. When I delete all the links in my post, it happens to be fine..

**Comment by wohfab** [comment]
The HTML request buffer from:
```
M-: (setq xml-rpc-debug 2) RET
```
gives me [THIS](http://pastebin.com/nVVAeqGw)

**Comment by punchagan** [comment]
Does this happen with any file or only some types of files?  Can you provide me a sample file? 

What version of Emacs are you using? What version of org-mode?

**Comment by grettke** [comment]
There isn't enough information to reproduce this. Please re-open it as your convenience.
