### ISSUE TITLE
(require org2blog-autoloads) fails

### ISSUE THREAD

**Issue by guybon** [org2blog/org2blog#185]
Hello
I'm using Ubuntu 14.04 lts and emacs 24.3.1
The error I get is 
...
     Warning (initialization): An error occurred while loading `/home/guy/.emacs':

```
 Symbol's value as variable is void: org2blog-autoloads
```

...
I set the in comment while it is not working.
the file exist. got user privileges.

org2blog portion of my .emacs file :
...
    ;; org2blog
    ;; org2blog dependencies
    (add-to-list 'load-path '“~/.emacs.d/elisps/metaweblog/”)
    (add-to-list 'load-path '“~/.emacs.d/elpa/xml-rpc-1.6.8/”)
    (add-to-list 'load-path '“~/.emacs.d/elpa/org2blog-0.5/”)
   ;(require 'org2blog-autoloads)

;; org2blog setup blog
(setq org2blog/wp-blog-alist
      '(("steptoharmony"
         :url "http://steptoharmony.wordpress.com/xmlrpc.php"
         :username "guybon"
         :default-title "Hello World"
         :default-categories ()
         :tags-as-categories nil)
       )
)
...

location of file :
...
.emacs.d/elpa/org2blog-0.5:
metaweblog.el   org2blog-autoloads.el   org2blog-autoloads.elc  org2blog.elc     org2blog-pkg.elc
metaweblog.elc  org2blog-autoloads.el~  org2blog.el             org2blog-pkg.el
...

Starting  emacs with  '--debug-init' gets this
...
Debugger entered--Lisp error: (file-error "Cannot open load file" "org2blog-autoloads")
  require(org2blog-autoloads)
  eval-buffer(#<buffer  *load*> nil "/home/guy/.emacs" nil t)  ; Reading at buffer position 1169
  load-with-code-conversion("/home/guy/.emacs" "/home/guy/.emacs" t t)
  load("~/.emacs" t t)

**Comment by punchagan** [comment]
Hi @guybon, I'm not sure what is going on here, though I don't see anything obviously wrong with your config.

**Comment by guybon** [comment]
The org2blog-autoload is in the 'features' list. With out the require i managed to log in.

**Comment by JulienRouse** [comment]
Hi @punchagan, i have the same problem as mentionned above, and when i comment
`(require 'org2blog-autoloads)`, emacs dont complain anymore.

But  then i try to login, and i get an error of type:
`Error bad username and/password`

I checked 20times already, so i come to ask here. I need the same username/password as when i connect to my wordpress account right?

Also, my .authinfo files looks like 
`machine my-machine login myusername  password mypassword`.
The name of the machine is relevant?

Sorry to bother you, any help appreciated

**Comment by grettke** [comment]
@guybon It sounds like it is resolved so I am closing this.
