### ISSUE TITLE
Attach an image as "Outstanding Image"?

### ISSUE THREAD

**Issue by drym3r** [org2blog/org2blog#186]
So that's the question. I've been reading the source (i'm new on lisp) but I do not see the way to put an image for every post. There's a way of doing it?

Thanks for your work, org2blog is amazing.

**Comment by punchagan** [comment]
Do you mean that you want to post the same image with all the posts?

**Comment by drym3r** [comment]
Note really, I'm talking about this.

![2015-06-01-115141_290x462_scrot](https://cloud.githubusercontent.com/assets/7255473/7910406/dd4b7ebc-0843-11e5-841f-56c2952e8f43.png)

It's an image you want to appear as a thumbnail on the index page and an upper image on the main post. You put one on every post.

**Comment by grettke** [comment]
It looks like you are referring to [featured posts](https://en.support.wordpress.com/featured-images/). That is a nice feature. Here are my thoughts:

org2blog uses metaweblog to post to WordPress. It is only concerned with the content for the blog post and not the WordPress post configuration. The [API](https://codex.wordpress.org/XML-RPC_MetaWeblog_API) doesn't provide configuration support, just blog post content support. So, I'm closing this feature: it is not supported by the API.
