### ISSUE TITLE
Posting fails in Emacs 25

### ISSUE THREAD

**Issue by higham** [org2blog/org2blog#187]
I get an error when posting from

GNU Emacs 25.0.50.1 (x86_64-w64-mingw32) of 2015-04-29 on KAEL
Org-mode version 8.2.10 (8.2.10-dist @ d:/Dropbox/elisp/org/lisp/)

The error is shown here (copied from message buffer):

Contacting host: nickhigham.wordpress.com:443
Opening TLS connection to `nickhigham.wordpress.com'...
Opening TLS connection with`gnutls-cli --insecure -p 443 nickhigham.wordpress.com'...done
Opening TLS connection to `nickhigham.wordpress.com'...done
url-http: Writing to process: Invalid argument, nickhigham.wordpress.com

I have the latest org2blog and other relevant packages.  My setup works
fine in

GNU Emacs 24.4.1 (x86_64-w64-mingw32) of 2014-10-21 on KAEL
Org-mode version 8.2.10 (8.2.10-dist @ d:/Dropbox/elisp/org/lisp/)

(in particular, a post was successfully made from 24.4.1 just after the failure above).

**Comment by higham** [comment]
I'm now using a newer compilation of Emacs and the version of org2blog from
about 7 days ago:

GNU Emacs 25.0.50.1 (x86_64-w64-mingw32) of 2015-11-10
Org-mode version 8.2.10 (8.2.10-dist @ d:/Dropbox/elisp/org/lisp/)

Posting now works fine. I think the problem was with the older Emacs binary.

**Comment by punchagan** [comment]
Thanks for posting the update.

**Comment by grettke** [comment]
Glad it ended up working out.
