### ISSUE TITLE
Conflict when post upload pdf file 

### ISSUE THREAD

**Issue by DiogoFerrari** [org2blog/org2blog#188]
If the emacs is set up to open the pdf file in a external program, the command org2blog/wp-post-buffer-as-page does not work. It opens the pdf in the external program and do not upload the post with the pdf.
Here is the emacs code for opening with external program:

(require 'openwith) ;; open pdf/other files in external app
(openwith-mode t) 
(setq openwith-associations)
(require 'mm-util);; prevent <openwith> from interfering with mail attachments
(add-to-list 'mm-inhibit-file-name-handlers 'openwith-file-handler)

Does someone know how to fix it?
Thanks

**Comment by DiogoFerrari** [comment]
It is still not working. Cant upload pdf in the post.

**Comment by grettke** [comment]
Closing this issue because it doesn't seem to be related to an Org2Blog feature, is not active, and it isn't obvious how to move forward with it. If work can start again then this task will get get re-opened.
