### ISSUE TITLE
Double backslash ('\\') in latex align environment not being exported

### ISSUE THREAD

**Issue by vinhdizzo** [org2blog/org2blog#199]
Hi,

I just pulled the latest org2blog, and would like to display multiline equations by using the latex align environment:

``` latex
\begin{align}
f(x) &= x_1 + x_2 \\
 &= x_3
\end{align}
```

However, when org2blog exports this, the &= get's translated into 

```
&#8211;
```

and the double backslashes ("\\") gets removed.  This is not the case when I do a normal org html export.  Because of the "\\" removal, I don't get multiline but rather, a long single line.  Is there a way to make org2blog not remove this during export?

I have the following in my .emacs:

``` lisp
(setq org2blog/wp-use-sourcecode-shortcode nil)
(setq org2blog/wp-use-wp-latex nil)
```

and the following in my org-mode file:

``` lisp
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil TeX:til
```

Thanks for your help and thanks for maintaining org2blog!

**Comment by grettke** [comment]
@vinhdizzo Thanks for your active involvement! This code is very to me and I don't know the answer right now either.

**Comment by vinhdizzo** [comment]
Are you the new maintainer? Is punchangan no longer maintaining the code? Thanks.

**Comment by grettke** [comment]
punchagan Is still a maintainer; I am co-maintaining. I just wanted to be transparent about why I didn't have an answer here.

**Comment by punchagan** [comment]
I'll take a look at it, as soon as I can. Sorry for being unresponsive.

**Comment by treese** [comment]
@vinhdizzo do you want the LaTeX rendered using MathJax? I tried a test using a MathJax plugin for Wordpress from https://wordpress.org/plugins/mathjax-latex/ and put the shortcode [mathjax] in the org source to trigger the plugin. The equations rendered nicely on the blog from that.

**Comment by vinhdizzo** [comment]
@treese my latex is rendered fine. The problem is the export removes double backslashes, hence losing multiline equations.

**Comment by treese** [comment]
@vinhdizzo With org-version 8.3.2 (I am tracking the current version from MELPA) and org2blog version 0.5, I'm not seeing that export problem now. I think I was able to reproduce it on an earlier version combination, but I don't have that now. Sorry I can't be of more help.

**Comment by vinhdizzo** [comment]
@treese I am using org 8.3beta (dev version).  I'm also using the dev version of org2blog.

**Comment by grettke** [comment]
OrgMode knows how to translate LaTeX fragments into HTML and LaTeX. But not WordPress. You need MathJax to tell WordPress to handle your fragments

Here https://github.com/org2blog/org2blog#mathjax-support are the directions to set it up along with samples.

Here https://www.wisdomandwonder.com/article/10675/org2blog-test-216 is an example if you want to see how it works using the fragment that you posted.

Let me know if you have any questions making it work for you.
