### ISSUE TITLE
SyntaxHighlighter does not work when posting source code blocks

### ISSUE THREAD

**Issue by zhizunbao84** [org2blog/org2blog#210]
i use emacs 24.5 and org-mod 8 in win 7, and below are what i do:
1. install packages:
M-x package-install RET xml-rpc
M-x package-install RET metaweblog
M-x package-install RET org2blog
M-x package-install RET htmlize
2. setting of org2blog in  .emacs.d/init.el:

(require 'htmlize-autoloads)
(require 'org2blog-autoloads)
(setq org2blog/wp-blog-alist
      '(("wordpress"
         :url "http://127.0.0.1/wordpress442/xmlrpc.php"
         :username "zhizunbao84"
         :default-title "Hello World"
         :default-categories ("other")
         :org2blog/wp-use-sourcecode-shortcode 
         :tags-as-categories nil)))
(setq wp-use-sourcecode-shortcode t)

3.install wordpress 4.4.2 with SyntaxHighlighter 3.2.1, and the setting of plugin SyntaxHighlighter is default.

the source code in my emacs:
![111111](https://cloud.githubusercontent.com/assets/2263408/13910159/aeb40e6e-ef58-11e5-9fa5-14727392d936.png)

it looks like in my blog:
![22222](https://cloud.githubusercontent.com/assets/2263408/13910162/b9ab355e-ef58-11e5-8012-13599cc65340.png)

it supposes to be:
![3333333](https://cloud.githubusercontent.com/assets/2263408/13910227/a7d80b26-ef59-11e5-8cfe-09ebcc770ace.png)

**Comment by grettke** [comment]
Looks like this https://github.com/org2blog/org2blog/issues/240 so marking it as resolved.
