### ISSUE TITLE
Crayon Syntax Highlighter can not work with org2blog?

### ISSUE THREAD

**Issue by ernest-dzf** [org2blog/org2blog#215]
I use Syntax Highlighter to highlight my code block, but it seems that org2blog can not work with Crayon Syntax Highlighter out of box.

What can I do to solve that problem?

**Comment by marcoimmel** [comment]
I had the same problem and wrote a new backend for org2blog, maybe it will help you also. You find it here https://gist.github.com/marcoimmel/79b7a58685d9da9f74ebbbd6aea2e42a

**Comment by grettke** [comment]
@ernest-dzf I don't see it supported in the code, no.

@marcoimmel It looks like you have and tested out this code with Org2Blog successfully. I've never used crayon before. What if you created a package for this, added it to MELPA and updated the README for how to use it?

**Comment by grettke** [comment]
You don't need a new exporter: use shortcodes with any plugin that you wish.

See [shortcodes in Org2Blog](https://github.com/org2blog/org2blog#posting-source-code-blocks)
