### ISSUE TITLE
When posting I get 'Lisp error: (wrong-type-argument listp t)'

### ISSUE THREAD

**Issue by zenshinji** [org2blog/org2blog#216]
GNU Emacs 24.5.1 (x86_64-w64-mingw32) of 2015-04-12 on KAEL
Org-mode version 8.3.4 (8.3.4-72-gddd58f-elpa @ c:/Users/prjor/.emacs.d/elpa/org-20160530/)
org2blog-20160502.1821 from ELPA

When I post the entry to my WP instance I get the above error. Here's the backtrace (short, so I won't pastebin it):

`Debugger entered--Lisp error: (wrong-type-argument listp t)
  org2blog/wp-save-details((("point" . 186) ("date" . "20160604T14:19:00+0000") ("title" . #("Hello, World" 0 12 (:parent (#("Hello, World" 0 12 (:parent #4)))))) ("description" . "<p> Another yet test</p>\n") ("tags") ("categories" "Uncategorized" "Hello") ("post-id") ("parent" . "0") ("excerpt" . "") ("permalink" . "")) "123" nil nil)
  org2blog/wp-post-buffer(nil)
  call-interactively(org2blog/wp-post-buffer record nil)
  command-execute(org2blog/wp-post-buffer record)
  helm-M-x(nil "org2blog/wp-post-buffer")
  call-interactively(helm-M-x nil nil)
  command-execute(helm-M-x)`

The entry does get written to my WP. I can continue to edit and post from Emacs but get the same error as I go. I tried replacing ELPA org2blog with the git version. No joy.

Thoughts?

**Comment by envypole** [comment]
I had a similar issue, the error disappeared after reinstallation of org package

**Comment by sideshowcoder** [comment]
Important to note here is that to reinstall org mode properly you need to remove all org specific settings temporarily from your initialization and then remove and reinstall org mode from elpa. This caught me because as long as there is still a custom setting for org mode it will be initialized on emacs startup and therefore won't reinstall properly, because of the built in version of org.

**Comment by zenshinji** [comment]
Thx @envypole @sideshowcoder. I tried w/ a clean 24.5.1 install with only my .authinfo.pgp & org2blog config (not via customize) brought over. Same issue. Can't figure out what is causing the problem. .authinfo.gpg is probably OK as ERC works fine with it + my blog post shows up. My org2blog config mostly just defines my sites.

**Comment by molten-steel** [comment]
I've got the same issue. How is org mode reinstalled? I can't see it in `M-x list-packages` at least on 26.0.50.1

**Comment by ctindall** [comment]
Anyone ever figure out the cause of this issue? I had everything working fine, and then I restarted emacs and had this issue. It's got to be something to do with my configuration/init, but I can't figure out what, since my org2blog config is really just my wp-blog-alist.

**Comment by ctindall** [comment]
FYI I was able to fix this by doing an M-x org-reload. YMMV but this seems like other an org bug or something goofy in my org-session, rather than something in org2blog.

**Comment by grettke** [comment]
This _sounds_ like a loading issue if reinstalling and re-loading solve the problem.

**Comment by zenshinji** [comment]
Diving back into the issue as it is still happening. Using org2blog & xml-rpc from GitHub, org-mode 9.0.9 from ELPA.

Here is the backtrace (sorry in advance if it is crazy big):

`  car(t)
  (if (plist-member (cdr org2blog/wp-blog) :track-posts) (car (plist-get (cdr org2blog/wp-blog) :track-posts)) (car org2blog/wp-track-posts))
  (if (if (plist-member (cdr org2blog/wp-blog) :track-posts) (car (plist-get (cdr org2blog/wp-blog) :track-posts)) (car org2blog/wp-track-posts)) (progn (let* ((o2b-id (if subtree-p (concat "id:" (org-id-get nil t)) (buffer-file-name))) (log-file (if (plist-member (cdr org2blog/wp-blog) :track-posts) (car (plist-get ... :track-posts)) (car org2blog/wp-track-posts))) (log-file (if (file-name-absolute-p log-file) log-file (if org-directory (expand-file-name log-file org-directory) (message "org-track-posts: filename is ambiguous\nuse absolute path or set org-directory") log-file))) (headline (if (plist-member (cdr org2blog/wp-blog) :track-posts) (car (cdr ...)) (car (cdr org2blog/wp-track-posts)))) p) (make-directory (file-name-directory log-file) t) (if o2b-id (progn (save-current-buffer (set-buffer (or ... ...)) (save-excursion (save-restriction ... ... ... ... ... ...) (org2blog/wp-update-details post o2b-id pid pub)) (save-buffer)))))))
  (save-excursion (if (if (plist-member (cdr org2blog/wp-blog) :track-posts) (car (plist-get (cdr org2blog/wp-blog) :track-posts)) (car org2blog/wp-track-posts)) (progn (let* ((o2b-id (if subtree-p (concat "id:" ...) (buffer-file-name))) (log-file (if (plist-member ... :track-posts) (car ...) (car org2blog/wp-track-posts))) (log-file (if (file-name-absolute-p log-file) log-file (if org-directory ... ... log-file))) (headline (if (plist-member ... :track-posts) (car ...) (car ...))) p) (make-directory (file-name-directory log-file) t) (if o2b-id (progn (save-current-buffer (set-buffer ...) (save-excursion ... ...) (save-buffer))))))))
  org2blog/wp-save-details((("point" . 204) ("date" . "20170812T04:46:00+0000") ("title" . "No Title") ("description" . "<p> This is a test.</p>\n") ("tags") ("categories" "Uncategorized" "org2blog") ("post-id" . "678") ("parent" . "0") ("excerpt" . "") ("permalink" . "")) "678" nil nil)
  (let ((post (org2blog/wp--export-as-post subtree-p)) (confirm (and (if (plist-member (cdr org2blog/wp-blog) :confirm) (plist-member (cdr org2blog/wp-blog) :confirm) org2blog/wp-confirm-post) publish)) (show (or (plist-member (cdr org2blog/wp-blog) :show) org2blog/wp-show-post-in-browser)) post-id) (org2blog/wp-create-categories (cdr (assoc "categories" post))) (setq post-id (cdr (assoc "post-id" post))) (if confirm (progn (if (not (y-or-n-p (format "Publish %s ?" (cdr ...)))) (error "Post cancelled.")))) (if post-id (metaweblog-edit-post org2blog/wp-server-xmlrpc-url org2blog/wp-server-userid org2blog/wp-server-pass post-id post publish) (progn (setq post-id (metaweblog-new-post org2blog/wp-server-xmlrpc-url org2blog/wp-server-userid org2blog/wp-server-pass org2blog/wp-server-blogid post publish)) (run-hook-with-args (quote org2blog/wp-after-new-post-or-page-functions) (org2blog/wp-get-post-or-page post-id))) (if subtree-p (progn (org-entry-put (point) "POSTID" post-id) (org-entry-put (point) "BLOG" org2blog/wp-blog-name)) (goto-char (point-min)) (insert (concat "#+BLOG: " org2blog/wp-blog-name "\n")) (insert (concat "#+POSTID: " post-id "\n")))) (org2blog/wp-save-details post post-id publish subtree-p) (message (if publish "Published (%s): %s" "Draft (%s): %s") post-id (cdr (assoc "title" post))) (if (or (equal show (quote show)) (and (equal show (quote ask)) (y-or-n-p "[For drafts, ensure you login] View in browser? y/n"))) (progn (if subtree-p (org2blog/wp-preview-subtree-post) (org2blog/wp-preview-buffer-post)))))
  (save-restriction (let ((post (org2blog/wp--export-as-post subtree-p)) (confirm (and (if (plist-member (cdr org2blog/wp-blog) :confirm) (plist-member (cdr org2blog/wp-blog) :confirm) org2blog/wp-confirm-post) publish)) (show (or (plist-member (cdr org2blog/wp-blog) :show) org2blog/wp-show-post-in-browser)) post-id) (org2blog/wp-create-categories (cdr (assoc "categories" post))) (setq post-id (cdr (assoc "post-id" post))) (if confirm (progn (if (not (y-or-n-p (format "Publish %s ?" ...))) (error "Post cancelled.")))) (if post-id (metaweblog-edit-post org2blog/wp-server-xmlrpc-url org2blog/wp-server-userid org2blog/wp-server-pass post-id post publish) (progn (setq post-id (metaweblog-new-post org2blog/wp-server-xmlrpc-url org2blog/wp-server-userid org2blog/wp-server-pass org2blog/wp-server-blogid post publish)) (run-hook-with-args (quote org2blog/wp-after-new-post-or-page-functions) (org2blog/wp-get-post-or-page post-id))) (if subtree-p (progn (org-entry-put (point) "POSTID" post-id) (org-entry-put (point) "BLOG" org2blog/wp-blog-name)) (goto-char (point-min)) (insert (concat "#+BLOG: " org2blog/wp-blog-name "\n")) (insert (concat "#+POSTID: " post-id "\n")))) (org2blog/wp-save-details post post-id publish subtree-p) (message (if publish "Published (%s): %s" "Draft (%s): %s") post-id (cdr (assoc "title" post))) (if (or (equal show (quote show)) (and (equal show (quote ask)) (y-or-n-p "[For drafts, ensure you login] View in browser? y/n"))) (progn (if subtree-p (org2blog/wp-preview-subtree-post) (org2blog/wp-preview-buffer-post))))))
  (save-excursion (save-restriction (let ((post (org2blog/wp--export-as-post subtree-p)) (confirm (and (if (plist-member ... :confirm) (plist-member ... :confirm) org2blog/wp-confirm-post) publish)) (show (or (plist-member (cdr org2blog/wp-blog) :show) org2blog/wp-show-post-in-browser)) post-id) (org2blog/wp-create-categories (cdr (assoc "categories" post))) (setq post-id (cdr (assoc "post-id" post))) (if confirm (progn (if (not (y-or-n-p ...)) (error "Post cancelled.")))) (if post-id (metaweblog-edit-post org2blog/wp-server-xmlrpc-url org2blog/wp-server-userid org2blog/wp-server-pass post-id post publish) (progn (setq post-id (metaweblog-new-post org2blog/wp-server-xmlrpc-url org2blog/wp-server-userid org2blog/wp-server-pass org2blog/wp-server-blogid post publish)) (run-hook-with-args (quote org2blog/wp-after-new-post-or-page-functions) (org2blog/wp-get-post-or-page post-id))) (if subtree-p (progn (org-entry-put (point) "POSTID" post-id) (org-entry-put (point) "BLOG" org2blog/wp-blog-name)) (goto-char (point-min)) (insert (concat "#+BLOG: " org2blog/wp-blog-name "\n")) (insert (concat "#+POSTID: " post-id "\n")))) (org2blog/wp-save-details post post-id publish subtree-p) (message (if publish "Published (%s): %s" "Draft (%s): %s") post-id (cdr (assoc "title" post))) (if (or (equal show (quote show)) (and (equal show (quote ask)) (y-or-n-p "[For drafts, ensure you login] View in browser? y/n"))) (progn (if subtree-p (org2blog/wp-preview-subtree-post) (org2blog/wp-preview-buffer-post)))))))
  org2blog/wp-post-buffer(nil)
  funcall-interactively(org2blog/wp-post-buffer nil)
  call-interactively(org2blog/wp-post-buffer record nil)
  command-execute(org2blog/wp-post-buffer record)
  #[257 "\304\305!\203\f`

**Comment by grettke** [comment]
@zenshinji I hear you.

**Comment by zenshinji** [comment]
I forgot to post this error: `error in process sentinel: Multibyte text in HTTP request: POST /xmlrpc.php HTTP/1.1`

**Comment by grettke** [comment]
Are you using this patched version of xml-rpc?

https://github.com/org2blog/org2blog/blob/master/README.org#unicode-character-support

**Comment by zenshinji** [comment]
Yes I am. I verified the version (1.6.12) and time stamp (`;; Last Modified: <2016-04-30 17:56:41 mah>`) are the same as the file to which you linked above. You can see how I am loading it here: https://github.com/zenshinji/emacs.d/blob/master/my_init.org#org2blog

I am fairly sure I deleted any other xml-rpc versions but I will double check just in case.

**Comment by zenshinji** [comment]
Ah ha! Well, maybe.

I blew away my ~/.emacs.d and started from scratch. Other than a too early call to use-package (which I fixed) it loaded up fine-ish.

Metaweblog keeps complaining about the GitHub version of xml-rpc. It wants to reinstall xml-rpc from MELPA. I think `package-selected-packages` in my customize file isn't doing me any favors either.

**Comment by zenshinji** [comment]
One more update - I got metaweblog (MELPA), org2blog (GitHub), and xml-rpc (GitHub) to finally play nice with each other in my config. Here is my test post:

`#+ORG2BLOG:
#+DATE: [2017-08-18 Fri 18:23]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil
#+CATEGORY: Uncategorized, org2blog
#+TAGS:
#+DESCRIPTION:
#+TITLE: Test

This is a test, people. Here’s an apostrophe. Here are “quotes”. & an ampersand, anyone?`

When I try to post after successful authentication I get `apply: Wrong type argument: listp, #("Test" 0 4 (:parent (#0)))`.

Let me know if you would like me to post the backtrace.

**Comment by grettke** [comment]
I just copied and pasted your post and successfully posted it [here](https://www.wisdomandwonder.com/article/10675/org2blog-test-216). The only difference is that I changed the title and tags, and that shouldn&rsquo;t matter. The apostrophe and double quotes from your post are still `non-ASCII` characters in my file. That would probably have blocked the post if it reached WordPress since the login mechanism didn&rsquo;t see any of those Unicode characters. So still, I *feel* like it might be a library load issue.

On my box I [load](https://github.com/grettke/help/blob/master/.org-mode-contribute.emacs.el) org mode, xml-rpc, and metaweblog from [source](https://github.com/grettke/osx-provision/blob/master/El-Capitan/18_org-mode.sh). That is easier for me. And I know that the correct version is getting loaded. Yes, that can be a hassle, but I know. Are you convinced the correct libraries are getting loaded?

Yes please post the backtrace.

**Comment by zenshinji** [comment]
The backtrace is here: http://www.prjorgensen.com/wp-content/uploads/2017/08/Backtrace.txt

I will try a new, clean instance & config with only org, org2blog, xml-rpc, and metaweblog while you poke at that.

**Comment by zenshinji** [comment]
Finally got 'round to poking at this again. Check out my post at http://www.prjorgensen.com/2017/08/25/troubleshooting-emacs-org2blog/ (done with org2blog) but basically it is working now as expected.

So yes, I did have some other package or something getting in my way. You have the backtrace if you want to dive in for other poor souls who trip on this. I will go back to redoing my config to make sure things stay Jake ('20s era slang).

Thanks for all the help. I am closing this as solved.

**Comment by grettke** [comment]
Every sounds Jake. Thanks for the update and have a great day.

**Comment by zenshinji** [comment]
One last thing - I got to the point of the original error in the OP. The solution is to set org-directory: e.g. `(setq org-directory "~/Dropbox/org")`. org2blog/wp-track-posts seems to rely on it.

**Comment by grettke** [comment]
https://github.com/org2blog/org2blog/issues/242
