### ISSUE TITLE
It uploads some of the pdf files, other it does not

### ISSUE THREAD

**Issue by DiogoFerrari** [org2blog/org2blog#219]
I have a link to different local pdf files. Some are uploaded, some are not. I am using the same link in all cases:

[[/path/to/file/file.pdf][pdf]]
[[/other/path/to/file/file2.pdf][pdf]]

Do you have any idea of what cause that behavior?

**Comment by grettke** [comment]
Gut reaction: does it make a difference when you use an external link prefix?

http://orgmode.org/manual/External-links.html

For example: `[[file:~/test.pdf][Foo]]`

**Comment by DiogoFerrari** [comment]
No, it didn't change anything, even including the prefix.

**Comment by grettke** [comment]
Please share some example files so that I can try to reproduce this behavior

**Comment by grettke** [comment]
Closing this issue because it is not active and it isn't obvious how to move forward with it. If work can start again then this task will get get re-opened.
