### ISSUE TITLE
Suggestion - Post downloads?

### ISSUE THREAD

**Issue by christoofar** [org2blog/org2blog#236]
It would be nice to suck down a start PostID -> stop PostID into a directory so that existing wordpress posts that are already on a site can be worked with (i.e grepped, updated, whatever).

It would also open the possibility of posting automated live updates (i.e. liveblog!) by grabbing an existing post, appending and re-uploading.   Easy to do if you wrote the post in .org to begin with.  Harder if another author did not do that.

**Comment by grettke** [comment]
@christoofar Try out [this script](https://github.com/punchagan/org2blog-importers/blob/master/wp_to_org2blog.py) to export an existing WordPress collection of posts. I used it to export all of my posts to individual files and it worked great.

About the live blogging idea I bet that something could be worked out in Elisp. How would you like to start hacking something like that up?

**Comment by grettke** [comment]
I will add a wishlist to capture your idea.

**Comment by sethm** [comment]
I'd like to echo my support for this idea, especially since I maintain my blog from several different computers, and have built up a large number of entries before I started using `org2blog`.

I'd like to be able to download a post or a page, edit it, and upload it again regardless of whether it was originally created with org-mode or not.

I know this is something of a tall order since it would necessitate translating arbitrary HTML into org-mode for editing, but I may try to contribute a pull request if it looks possible.

**Comment by punchagan** [comment]
#130 also seems to suggest something similar, though, it probably got side-tracked. 

One idea could be to enable this for posts which have been written using org2blog, by possibly appending the org-mode source text as a comment on the post.  If we find this comment text, we could fetch it, and re-create the org-file.  We avoid the need for fancy html2org converters. 

Another idea could be to use pandoc to convert from html to org-mode. Pandoc's support for orgmode has gotten really good, in the last couple of years or so.

**Comment by grettke** [comment]
@sethm Tell me if I understand you correctly, do I?

- WordPress is your "master data source"
- You maintain your WordPress instance from multiple computers via a web browser. So the version of the post on the server is always the correct one. You might edit it with the web browser, Emacs, or an app on your phone. It doesn't matter: WordPress is the master.
- Sometimes you want to open up a post in Emacs, make changes, and push the changes back to your WordPress instance
- Using Emacs, you don't care about saving that post to a file, and you don't care about synchronizing that file between itself and the post out on the server. Org2Blog becomes a client/server app for WordPress.

If I understand correctly then we must take the version on the server and convert it to Org-Mode every time you edit the post, so it would look like this:

- Install Pandoc
- Refactor the export code from [here](https://github.com/punchagan/org2blog-importers/blob/master/wp_to_org2blog.py) to work for a single post for which you know the ID
- Call out the shell to export that one post, save that to a temp file, open it in Emacs, make changes, and publish it to WordPress, the temp file goes away
- Nothing left to do.

Using Org2Blog as a client/server app is interesting. It turns the idea of Org2Blog on its head a little bit making it Blog2Org2Blog :). 

Here is what you should do:

Use [this](https://github.com/punchagan/org2blog-importers/blob/master/wp_to_org2blog.py) script to get an exported copy of your database as Org2Blog files. 

Then open up your most cherished and/or complex posts and see if you are happy with how Pandoc exported the post. Do it for at least 30 posts to get a really good sense of whether you want to work the Pandoc conversion or not. 

The success of this feature, as I understand it, depends 100% on how well you like or dislike the Pandoc conversion.

What do you think?

**Comment by sethm** [comment]
@grettke You have it exactly right, that's precisely the work flow I'm after. I think you're right on the nose with the correct sequence of actions to take in regards to exporting my blog from wordpress. I've used the wp_to_org2blog.py script quite successfully, though I'd like to continue to tweak the panadoc settings a bit. I'll let you know what I discover!

**Comment by lockywolf** [comment]
I would be happy enough if org2blog could just download the original HTML.

Most of my blog posts are written (by me) in the html editor of wordpress, so it is quite human-readable.

Although it would sort of take the actual 'org' out of there, but it could be brought back by just prepending everything with #+begin_export html and appending with +end_export html

**Comment by grettke** [comment]
@sethm On revisiting this I can see it is just too much of a change from Org2Blog into Blog2Org2Blog. Glad you tried the converter. Of course requests are welcome for such functionality. If you want to develop something I'm glad to set up the branch and give your an overview of the system.

**Comment by grettke** [comment]
@lockywolf Use [this](https://github.com/org2blog/org2blog-importers/blob/master/wp_to_org2blog.py) script to get an exported copy of your database as Org2Blog files. Then like you said you can wrap the content in an HTML block and you got it.

**Comment by grettke** [comment]
@punchagan Attaching the original Org file is an excellent idea. The same problems remain though in that when the post-on-the-server becomes newer than the original source file we'll still have to convert it with Pandoc or something.

**Comment by grettke** [comment]
There is a lot of discussion and brainstorming in this thread which explains the use case and the context of everything. For every approach we discussed they all come down to having to handle posts-data get out-of-sync between the source and destination because it is in two-directions and additionally require something like Pandoc. Right now I don't want to add a dependency on Pandoc for posting from Org-to-Blog and additionally it is too far out of scope to a bi-directional workflow. Like we said above it would change Org2Blog into Blog2Org2Blog. That is a great workflow and I like it too but it would be too much work for now. That said contributions are welcome I will gladly set up a branch, introduce the code to you, and go wherever that takes us.
