### ISSUE TITLE
Release a 1.0 version

### ISSUE THREAD

**Issue by grettke** [org2blog/org2blog#237]
This software is ready for a major release at v1.0.0.

**Comment by grettke** [comment]
@punchagan I swear that I did not intentionally make this commit exactly 7 years later. I am astounded.

**Comment by punchagan** [comment]
Awesome!  Congratulations on the new release, @grettke ! :tada: :champagne:

**Comment by grettke** [comment]
@punchagan Your first commit on this repo was exactly seven years ago today. I did not plan this release to be on this particular date. So this was a really nice surprise! Thank you for making this happen!
