### ISSUE TITLE
#+NAME doesn't work

### ISSUE THREAD

**Issue by aspiers** [org2blog/org2blog#239]
I just tried to give a section in one of my posts a named anchor as per [the org-mode docs](http://orgmode.org/manual/Internal-links.html):

    #+NAME: foo
    ** foo section

but after republishing, no evidence of the anchor appeared on Wordpress.  Am I doing something wrong?

**Comment by grettke** [comment]
Here is how I am looking into it because I don&rsquo;t know:

Here is the Emacs and Org-Mode that I am using. I am loading [this](https://github.com/grettke/help/blob/master/.org-mode-ecm.emacs.el) config, but nothing else. So we should be able to reproduce whatever we find.

    <<<ECM Information>>>
    This buffer file: nil
    As Of: 2017-08-18T11-15-50
    Org-Version: 9.0.9
    Org-Git-Version:release_9.0.9-773-gd0ced9
    Emacs-Version: GNU Emacs 25.2.1 (x86_64-apple-darwin15.6.0, Carbon Version 157 AppKit 1404.47)
     of 2017-07-28

Here is my test file

```org
Hi.

#+NAME: robot
** foo section

There.
```

When I export it to HTML directly I see these relevant parts

```html
<p>
Hi.
</p>
<div id="outline-container-orgf43eb09" class="outline-2">
<h2 id="orgf43eb09"><span class="section-number-2">1</span> foo section</h2>
<div class="outline-text-2" id="text-1">
<p>
There.
</p>
</div>
```

I don&rsquo;t see the id `robot` mentioned in there.

Should it be? What do you see?

I now that o2b uses that generated HTML to make the post, so `robot` ought to be in there.

**Comment by aspiers** [comment]
That corresponds exactly to what I see in [the blog post I was testing this with](https://blog.adamspiers.org/2017/08/16/squash-merging-and-other-problems-with-github/).  The source has:

```
#+NAME: use-the-force
*** Use the force-push, Luke
```

and if you inspect that `<h2>` header, you'll see the same `<div>`s on either side, but no anchor.  And I  would expect something like `<a name="robot">` (in your example).  I guess it's time to ask for help on the org-mode mailing list?

**Comment by grettke** [comment]
That is what I would do since neither of us can get it to work in Org-Mode.

If you feel good about this resolution then please close this issue.

**Comment by aspiers** [comment]
I'll post to the list, but I'd prefer to keep this issue open until it is actually resolved.

**Comment by aspiers** [comment]
Oh, it just occurred to me that it is possible to directly test org-mode's HTML export! So I pressed `C-c C-e h H` to export to an HTML buffer, and sure enough the anchor is missing there.  So either `#+NAME` is not supposed to do this and we're misunderstanding something, or there's a bug in HTML export.

**Comment by aspiers** [comment]
... and after reading http://orgmode.org/manual/Internal-links.html#Internal-links more carefully, I found that anchors for headlines can be created by setting a `CUSTOM_ID` property!  However this still doesn't answer how to set anchors for other elements, so I just emailed the list after all.

**Comment by grettke** [comment]
I hear you.

**Comment by aspiers** [comment]
I got a reply which I think is sufficient to close this:

http://lists.gnu.org/archive/html/emacs-orgmode/2017-08/msg00437.html
