### ISSUE TITLE
Possible correction for README: htmlize source

### ISSUE THREAD

**Issue by priyadarshan** [org2blog/org2blog#241]
The README says that `htmlize.el` is available in org-mode’s contrib/lisp.
https://github.com/org2blog/org2blog#posting-source-code-blocks

Having installed latest `org` and `org-contrib` via melpa, it seems  such directory is not available.

I was able to install `htmlize.el` via melpa package though: http://melpa.org/#/htmlize

**Comment by grettke** [comment]
@priyadarshan I'm pretty sure that I read on the org-mode mailing list that htmlize was removed from the contrib directory. So the document definitely needs an update.

**Comment by priyadarshan** [comment]
Thank you for checking that, and thank you for org2blog. I would not be using Emacs if not for it. It is quite empowering.

**Comment by grettke** [comment]
htmlize was removed from org's repo here http://orgmode.org/cgit.cgi/org-mode.git/commit/?id=d0ced98943da0e5851ba1145515db27e939bff08

I will update the docs.

**Comment by grettke** [comment]
And the source code and package def, too.
