### ISSUE TITLE
Textlink results in 503 error

### ISSUE THREAD

**Issue by e11bits** [org2blog/org2blog#246]
I have this org file:

`#+BLOG: e11bits`
`#+POSTID: 51`
`#+ORG2BLOG:`
`#+DATE: [2017-08-28 Mo 23:37]`
`#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil`
`#+CATEGORY: org2blog, emacs`
`#+TAGS:`
`#+DESCRIPTION:`
`#+TITLE: Setting up a blog with Org2Blog`

`[[http://orgmode.org/][Org mode]] for [[https://www.gnu.org/software/emacs/][Emacs]] is advertised` 

If I try to upload this I get a 503 error. Now when I remove the second link the upload is fine.

I have these set:

`'(org2blog/wp-use-sourcecode-shortcode t)`
`'(org2blog/wp-use-wp-latex nil)`

I've used commit 62a6400746847f246e12493271f0bb52f7465a92 and my installation can be reproduced by a little script of mine at https://github.com/e11bits/org2bloginstall

**Comment by e11bits** [comment]
Org mode version 9.0.7 (9.0.7-elpa @ ~/.emacs.d/elpa/org-20170515/)
Wordpress 4.8.1

**Comment by grettke** [comment]
I hear you @e11bits .

**Comment by grettke** [comment]
@e11bits Thank you for the detail. As soon as I start working on this I will let you know ASAP.

**Comment by grettke** [comment]
@e11bits Is this a blocker for you right now or can you work around it until it is fixed?

**Comment by e11bits** [comment]
@grettke The workaround is to avoid links as much as possible. It's annoying, but not a showstopper.

**Comment by grettke** [comment]
@e11bits Glad to hear and thanks for letting me know.

**Comment by grettke** [comment]
@e11bits Just tried it today and it worked as expected. Does it work for you?

**Comment by grettke** [comment]
Closing this issue because it is not active and it was obvious how to move forward with it. It should be resolved now. If work needs to restart then this task will get get re-opened.
