### ISSUE TITLE
Revert to draft

### ISSUE THREAD

**Issue by priyadarshan** [org2blog/org2blog#247]
Hello,

A few times I had the need to revert a published post or page to `draft` status.

I could not find a way yet, so I push the post again with a date set in the far future.

Short of deleting the entry, removing `POST-ID` and re-submitting it as draft, is there a way one could revert a post to `draft` status?

I would prefer not to do that, as I rely on `POST-ID` and the above method would of course assign a new `POST-ID`.

**Comment by grettke** [comment]
Org2Blog uses [MetaWeblog for Elisp](https://github.com/org2blog/metaweblog/blob/master/metaweblog.el). The standard is [here](https://en.wikipedia.org/wiki/MetaWeblog). Have a look and see if something like that is possible with the API. 

Either way then let's talk about possible next steps.

**Comment by priyadarshan** [comment]
Nice, one can use the full WP XML-RPC API:
https://codex.wordpress.org/XML-RPC_WordPress_API

I am not fluent with coding, but it seems that one can edit a post with `wp.editPost`:
https://codex.wordpress.org/XML-RPC_WordPress_API/Posts

I am guessing one could specify the parameter `post_status`, setting it to "Draft"?

**Comment by grettke** [comment]
Gotcha. That is a good place to start. First, I need help understanding what you want and expect to see. Here is what I am seeing:

- Using [this post](https://www.wisdomandwonder.com/article/10675/org2blog-test-216)
- It was previously published
- I changed the state of it to draft and saved the post
- I went to that URL, it was accessible, and it looked exactly the same

The post id remained the same and the page remained visible at the same url.

Is this what you expected? Is my blog set up the same way as yours?

**Comment by priyadarshan** [comment]
Thank you for taking the time considering this.

This is what I see on a vanilla WP site:

- Post has `Published` status,
I can see it from any browser, while I am logged in, or browsing as anonymous user.

- Post status is changed to `Draft`
I can still see it from the browser where I am logged in as admin,
If I navigate using another browser, as anonymous user, the post is not accessible anymore (404).

**Comment by grettke** [comment]
Thanks for explaining that because I was logged in as admin the whole time.

I _will_ pick this up again.

**Comment by priyadarshan** [comment]
Acting on a hunch, I simply tried `org2blog/wp-post-subtree` on a selected subtree, and it reverted its status from published to draft.
So, this issue could be closed. Perhaps it would be nice to mention clearly in the README that one can revert status to draft simply by calling `org2blog/wp-post-subtree` or `org2blog/wp-post-buffer`.
Thank you @grettke for your availability and patience.

**Comment by grettke** [comment]
That is good to know.

To me it sounds like surprising behavior because it changes a published post to an un-published post. I need to learn how this works so I'm leaving it open.

Thank you for your detailed and thoughtful reports and collaboration.

**Comment by grettke** [comment]
@priyadarshan I renamed the functions to be simpler and consistent. For example there is now `org2blog-buffer-post-save` to save your changes as a draft and `org2blog-buffer-post-publish` to post those changes. The language `post` and `publish` is the language that WordPress uses for performing those actions instead of the techie way of saying it (behind the scenes it is an XML service call).

When you look at it this way does it work the way you expect it?

When you do post an entry, it has to change the status to Draft because it is a draft unless you publish it immediately.

**Comment by priyadarshan** [comment]
> When you look at it this way does it work the way you expect it?

Yes, thank you, that makes perfect sense.

Thank you for maintaining org2blog and improving it over time to such useful tool.

Thanks for the shiny nice logo, too!

**Comment by grettke** [comment]
Sounds good. Thanks for sharing your questions and have fun blogging.
