### ISSUE TITLE
Feature request: use org-mode #+include

### ISSUE THREAD

**Issue by priyadarshan** [org2blog/org2blog#248]
It would be nice to be able to use org-mode `#+include` feature:
http://orgmode.org/manual/Include-files.html

At the moment ort2blog will not publish a post with that directive, but rather write the whole buffer plus some xml to the `*message*` buffer.

With this new feature, org2blog would be able to include files as text, but also deal with source code, something like:

```
#+NAME: tmux.conf
#+INCLUDE: "~/.tmux.conf" src sh 
```

As a use case, one could maintain source files elsewhere, and still publish them, making it easy to update at will.

**Comment by grettke** [comment]
That sounds like a great feature.

Acknowledged.

**Comment by priyadarshan** [comment]
My bad, patched xml-rpc.el was not loaded.

Now that it is, the above syntax works fine for regular include.

If one wants to get the include as a src, like snippet above, it will still publish it as regular HTML though.

**Comment by grettke** [comment]
@priyadarshan Thanks for the update. Closing.
