### ISSUE TITLE
Use org2blog for editing pages?

### ISSUE THREAD

**Issue by nneuss** [org2blog/org2blog#258]
Hi,
at the moment I don't know much about Wordpress or org2blog, but our math department at the FAU Erlangen-Nuernberg is just switching from Typo3 to Wordpress for its web pages and I very much would like to work with Emacs instead of the Wordpress editor.
Therefore I wan to ask if it is possible to use org2blog also for editing web pages instead of posts?
And if yes, could someone maybe provide a small example?
Thank you very much,
Nicolas

**Comment by grettke** [comment]
Hi @nneuss ,

Yes you can edit pages, too. 

For example [this Org mode document](https://raw.githubusercontent.com/grettke/wisdomandwonder/master/page/About.org)
 creates this [web page](https://www.wisdomandwonder.com/about).
