### ISSUE TITLE
Can't login: Error during request: 400

### ISSUE THREAD

**Issue by vnckppl** [org2blog/org2blog#264]
My setup is:
org2blog-1.0.3 (via elpa)
xml-rpc-1.6.12 (installed as dependecy)
org-20190304

I have added the following to my .emacs
```
;; org2blog
(add-to-list 'load-path "/Users/myLocalUsername/.emacs.d/elpa/org2blog-1.0.3")
(require 'org2blog-autoloads)

;; org2blog: Wordpress Credentials
(setq org2blog/wp-blog-alist
      '(("wordpress"
         :url "https://myWPUsername.wordpress.com/xmlrpc.php"
         :username "myWPUsername"
         )))
```

When I do: 

M-x org2blog/wp-login

I get an error. \*Messages\* shows:

> Contacting host: myWPUsername.wordpress.com:443
> progn: Error during request: 400

I have no plugins installed for Wordpress.

Is there something obvious I am missing? Thanks for your help!

**Comment by grettke** [comment]
Hi @vnckppl . It looks like you are reaching WordPress and it is saying that there is [something](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400) wrong with the request. The best way for us to move forward is to enable as much debugging as possible. There are a few things we can get from that:

1. Find a detailed error message
2. Find out wha library the issue occurred in
3. Reproduce the issue using cURL to find out if the issue is WordPress, a library, or Org2Blog.

Please enable all debugging [like this](https://gist.github.com/grettke/72c3036eed1eba641411a72c5828c7cb). View the buffers mentioned. I think the quest place to start is looking at the buffer `*URL-DEBUG*`. 

Read it. Is it what you expect? Please share here if it makes sense. Be sure to remove your username and password and other private information because it is all in the debug buffer.n

Another thing that you can try, and it is simpler, is to open the buffer `request-data`. You can copy its contents into a file named test.xml and send it to your blog with cUrl like this:

curl --data @test.xml https://myWPUsername.wordpress.com/xmlrpc.php

to see if you get the same error or not. That way we can start to deduce where in what layer is the issue happening.

**Comment by vnckppl** [comment]
Hi @grettke! Thank you for your feedbabck. 

I enabled the debugging via the information from what you wrote here:

I am not sure about the request-data buffer. Should that be generated when I run org2blog/wp-login?

Here is the output from \*messages\* with debugging enabled:

> Contacting host: myWPUsername.wordpress.com:443
> gnutls.c: [1] (Emacs) connecting to host: myWPUsername.wordpress.com
> gnutls.c: [1] (Emacs) allocating credentials
> gnutls.c: [2] (Emacs) allocating x509 credentials
> gnutls.c: [2] (Emacs) using default verification flags
> gnutls.c: [audit] There was a non-CA certificate in the trusted list: O=Entrust.net,OU=www.entrust.net/CPS_2048 incorp. by ref. (limits liab.),OU=(c) 1999 Entrust.net Limited,CN=Entrust.net Certification Authority (2048).
> 
> gnutls.c: [1] (Emacs) setting the trustfile:  /etc/ssl/cert.pem
> gnutls.c: [1] (Emacs) gnutls callbacks
> gnutls.c: [1] (Emacs) gnutls_init
> gnutls.c: [1] (Emacs) got non-default priority string: NORMAL:%DUMBFW
> gnutls.c: [1] (Emacs) setting the priority string
> gnutls.c: [2] added 6 protocols, 29 ciphersuites, 18 sig algos and 9 groups into priority list
> 
> gnutls.c: [audit] Note that the security level of the Diffie-Hellman key exchange has been lowered to 256 bits and this may allow decryption of the session data
> 
> gnutls.c: [2] Keeping ciphersuite 13.02 (GNUTLS_AES_256_GCM_SHA384)
> 
> gnutls.c: [2] Keeping ciphersuite 13.03 (GNUTLS_CHACHA20_POLY1305_SHA256)
> 
> gnutls.c: [2] Keeping ciphersuite 13.01 (GNUTLS_AES_128_GCM_SHA256)
> 
> gnutls.c: [2] Keeping ciphersuite 13.04 (GNUTLS_AES_128_CCM_SHA256)
> 
> gnutls.c: [2] Keeping ciphersuite c0.2c (GNUTLS_ECDHE_ECDSA_AES_256_GCM_SHA384)
> 
> gnutls.c: [2] Keeping ciphersuite cc.a9 (GNUTLS_ECDHE_ECDSA_CHACHA20_POLY1305)
> 
> gnutls.c: [2] Keeping ciphersuite c0.ad (GNUTLS_ECDHE_ECDSA_AES_256_CCM)
> 
> gnutls.c: [2] Keeping ciphersuite c0.0a (GNUTLS_ECDHE_ECDSA_AES_256_CBC_SHA1)
> 
> gnutls.c: [2] Keeping ciphersuite c0.2b (GNUTLS_ECDHE_ECDSA_AES_128_GCM_SHA256)
> 
> gnutls.c: [2] Keeping ciphersuite c0.ac (GNUTLS_ECDHE_ECDSA_AES_128_CCM)
> 
> gnutls.c: [2] Keeping ciphersuite c0.09 (GNUTLS_ECDHE_ECDSA_AES_128_CBC_SHA1)
> 
> gnutls.c: [2] Keeping ciphersuite c0.30 (GNUTLS_ECDHE_RSA_AES_256_GCM_SHA384)
> 
> gnutls.c: [2] Keeping ciphersuite cc.a8 (GNUTLS_ECDHE_RSA_CHACHA20_POLY1305)
> 
> gnutls.c: [2] Keeping ciphersuite c0.14 (GNUTLS_ECDHE_RSA_AES_256_CBC_SHA1)
> 
> gnutls.c: [2] Keeping ciphersuite c0.2f (GNUTLS_ECDHE_RSA_AES_128_GCM_SHA256)
> 
> gnutls.c: [2] Keeping ciphersuite c0.13 (GNUTLS_ECDHE_RSA_AES_128_CBC_SHA1)
> 
> gnutls.c: [2] Keeping ciphersuite 00.9d (GNUTLS_RSA_AES_256_GCM_SHA384)
> 
> gnutls.c: [2] Keeping ciphersuite c0.9d (GNUTLS_RSA_AES_256_CCM)
> 
> gnutls.c: [2] Keeping ciphersuite 00.35 (GNUTLS_RSA_AES_256_CBC_SHA1)
> 
> gnutls.c: [2] Keeping ciphersuite 00.9c (GNUTLS_RSA_AES_128_GCM_SHA256)
> 
> gnutls.c: [2] Keeping ciphersuite c0.9c (GNUTLS_RSA_AES_128_CCM)
> 
> gnutls.c: [2] Keeping ciphersuite 00.2f (GNUTLS_RSA_AES_128_CBC_SHA1)
> 
> gnutls.c: [2] Keeping ciphersuite 00.9f (GNUTLS_DHE_RSA_AES_256_GCM_SHA384)
> 
> gnutls.c: [2] Keeping ciphersuite cc.aa (GNUTLS_DHE_RSA_CHACHA20_POLY1305)
> 
> gnutls.c: [2] Keeping ciphersuite c0.9f (GNUTLS_DHE_RSA_AES_256_CCM)
> 
> gnutls.c: [2] Keeping ciphersuite 00.39 (GNUTLS_DHE_RSA_AES_256_CBC_SHA1)
> 
> gnutls.c: [2] Keeping ciphersuite 00.9e (GNUTLS_DHE_RSA_AES_128_GCM_SHA256)
> 
> gnutls.c: [2] Keeping ciphersuite c0.9e (GNUTLS_DHE_RSA_AES_128_CCM)
> 
> gnutls.c: [2] Keeping ciphersuite 00.33 (GNUTLS_DHE_RSA_AES_128_CBC_SHA1)
> 
> gnutls.c: [2] Advertizing version 3.4
> 
> gnutls.c: [2] Advertizing version 3.3
> 
> gnutls.c: [2] Advertizing version 3.2
> 
> gnutls.c: [2] Advertizing version 3.1
> 
> gnutls.c: [2] HSK[0x103553600]: sent server name: 'myWPUsername.wordpress.com'
> 
> gnutls.c: [1] (Emacs) non-fatal error: Resource temporarily unavailable, try again. [208 times]
> gnutls.c: [2] EXT[0x103553600]: client generated SECP256R1 shared key
> 
> gnutls.c: [1] (Emacs) non-fatal error: Resource temporarily unavailable, try again.
> gnutls.c: [2] (Emacs) Deallocating x509 credentials
> progn: Error during request: 400

**Comment by grettke** [comment]
When you log in, Org2Blog asks WordPress for all of its categories. That way Category completion works when you are writing you entry. For that reason, yes that buffer should be created. It contains the message sent to the server. It looks like this:

`
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<methodCall>
  <methodName>metaWeblog.getCategories</methodName>
  <params>
    <param>
      <value>
        <string>1</string>
      </value>
    </param>
    <param>
      <value>
        <string>username</string>
      </value>
    </param>
    <param>
      <value>
        <string>password</string>
      </value>
    </param>
  </params>
</methodCall>
"
`

Does your look the same? I think that it probably does. If so, then copy that and paste it into text.xml, install cUrl, and run it like I showed up there. In this way, we can determine if the issue is with Emacs or if it is with the server. I have some ideas about what is going on here because I ran into something sort of like that a month or so ago. 

What operating system are you running this on?

I'm going offline now so I'll reply tomorrow. Have a good one.

**Comment by vnckppl** [comment]
Thanks! Here is what the script spat back out:

> <?xml version="1.0" encoding="UTF-8"?>
> <methodResponse>
>   <params>
>     <param>
>       <value>
>       <array><data>
>   <value><struct>
>   <member><name>categoryId</name><value><int>8</int></value></member>
>   <member><name>parentId</name><value><int>0</int></value></member>
>   <member><name>description</name><value><string>test</string></value></member>
>   <member><name>categoryDescription</name><value><string></string></value></member>
>   <member><name>categoryName</name><value><string>test</string></value></member>
>   <member><name>htmlUrl</name><value><string>https://myWPUsername.wordpress.com/category/test/</string></value></member>
>   <member><name>rssUrl</name><value><string>https://myWPUsername.wordpress.com/category/test/feed/</string></value></member>
> </struct></value>
>   <value><struct>
>   <member><name>categoryId</name><value><int>1</int></value></member>
>   <member><name>parentId</name><value><int>0</int></value></member>
>   <member><name>description</name><value><string>Uncategorized</string></value></member>
>   <member><name>categoryDescription</name><value><string></string></value></member>
>   <member><name>categoryName</name><value><string>Uncategorized</string></value></member>
>   <member><name>htmlUrl</name><value><string>https://myWPUsername.wordpress.com/category/uncategorized/</string></value></member>
>   <member><name>rssUrl</name><value><string>https://myWPUsername.wordpress.com/category/uncategorized/feed/</string></value></member>
> </struct></value>
> </data></array>
>       </value>
>     </param>
>   </params>
> </methodResponse>

Indeed, I only have a test category set up so far.

I am currently working on OSX 10.12.6. 
To see if there is anything wrong with my emacs (v26.1) setup I have removed my init files and folders and started installing packages from scratch. This did not resolve the issue.

Interestingly, I have a PixelBook with an almost identical emacs/org setup that does let me login with org2blog.

**Comment by grettke** [comment]
I'm on macOS by the way, 10.12.6 Sierra.

So when you send the XML using cCurl the call works and you get a result, but the same thing from Emacs doesn't work, right? If we narrowed that down, then, that is a good start. 

Last month I ran into an issue with TLS. I am not a TLS person but I tried to narrow it down and got something that worked. Here was my solution:

`(setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3")`

along with [why](https://github.com/org2blog/org2blog/blob/wip/docs/DebuggingStories.org)

Today I searched the web for your error message and found two articles that seem to have to do with TLS and Emacs, too, they came up with your error:

- https://www.reddit.com/r/emacs/comments/3sjdyi/your_text_editor_is_malware/cxfol83/
- https://glyph.twistedmatrix.com/2015/11/editor-malware.html

If you try out the snippet I posted, then add it to your init and restart Emacs. Once that value is setup you can't change it during the time that Emacs is open. If you change it then you have to restart Emacs again. 

In my notes I used WireShark to figure out what was going on. Not saying we need to do that here, but, it is a tool available for us.

Whether this is the issue or not, we can see that you and I are not alone here, and that a bunch of people have faced some issue with TLS, and resolved it. So know that you will soon be blogging: we will keep at it.

Let me know what you find.

**Comment by vnckppl** [comment]
Adding `(setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3")` did the trick. Thanks a bunch! This is great.

- Vincent

**Comment by grettke** [comment]
That is great news!

Let me know if you need anything else. I'm re-writing a bunch of things right now in the [wip](https://github.com/org2blog/org2blog/tree/wip) branch so if you notice areas for improvement, please share :).

**Comment by vincent-picaud** [comment]
> (setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3")

I've had the same problem (443 error) since eternity. This did the trick too. Thanks!

**Comment by grettke** [comment]
@vincent-picaud That is great new! Thanks for letting us know.
