### ISSUE TITLE
Administrator access to testorg2blog.wordpress.com

### ISSUE THREAD

**Issue by grettke** [org2blog/org2blog#265]
Please add me @grettke as an Aministrator

https://en.support.wordpress.com/adding-users/

to

https://testorg2blog.wordpress.com/

so I can run and take over the tests.

My WordPress ID is 'grettke'.

**Comment by punchagan** [comment]
@grettke I don't seem to recall how I signed up for this account, and am unable to figure out the credentials for this blog! :see_no_evil:

**Comment by grettke** [comment]
I hear you that is so easy for that to happen :). 

Do you think if you email them then they would "remind" you?

I've been thinking about using Docker to run the tests. I fear it might be too heavyweight though.

**Comment by punchagan** [comment]
I wasn't able to figure out the email with which I signed up. I've now invited you, after I found that! :)

**Comment by punchagan** [comment]
Using Docker might indeed be too heavy weight, but if tests can run more reliably and on branches of forks, etc., it may be worth doing. :thinking:

**Comment by grettke** [comment]
Thank you I am set up as an admin.

**Comment by grettke** [comment]
You know if they didn't mind, I could just set up a blog for each branch. That would solve the share development testing scenario at least. For personal branches though, yea, maybe Docker at some point.
