### ISSUE TITLE
Location of .org2blog

### ISSUE THREAD

**Issue by vnckppl** [org2blog/org2blog#267]
Is it possible to move .org2blog to the root of my home folder instead storing it in under ~/org/.org2bog?

**Comment by grettke** [comment]
Hi @vnckppl Org mode defines the value `org-directory`. It is a directory (specified by a string). Org2Blog places the `.org2blog` file within that directory. I think that fastest way to get what you want would be to:

    (setq org-directory "~/") ; Specify what "home directory" means to you

and then maybe call `org-reload`. 

Be sure to read the documentation for that variable, too.

Does this work for you?

I [added](https://github.com/org2blog/org2blog/issues/268) a feature request to add a customization for the location of the file.

**Comment by vnckppl** [comment]
Thanks!! That seems to work.

**Comment by grettke** [comment]
@vnckppl Excellent. Thanks for reaching out. Happy blogging!
