### ISSUE TITLE
The 'Usage' wiki page is not easy to understand in the 'Dashboard' section.

### ISSUE THREAD

**Issue by lockywolf** [org2blog/org2blog#270]
Thank you for filing this bug report. To make it easier for you and easier for
us please answer these five short questions:

- What version of Org2Blog are you using (`org2blog/wp-version`)?
      20190309.442 from MELPA. Also, there is not org2blog/wp-version in this version. 

- Did you review the wiki or the issues to see if this bug is already explained or reported?

Yes. The wiki says:
> This is meant to be a dashboard of sorts, and is an optional feature disabled by default. 

But doesn't say how to enable it or how to use it.

- What did you do?

Asked on the bugtracker.

- What did you expect to see?

A function to open the dashboard.

- What did you see instead?

Nothing.

**Comment by grettke** [comment]
@lockywolf I hear you. Have you read the documentation for `org2blog/wp-track-posts`?

**Comment by grettke** [comment]
Please feel free to open this again if you want to go further with it.
