### ISSUE TITLE
Setting the ‘Post Kind’ via org2blog

### ISSUE THREAD

**Issue by shrysr** [org2blog/org2blog#277]
- What version of Org2Blog are you using (`org2blog/wp-version`)?  1.03
- Did you review the wiki or the issues to see if this bug is already explained or reported? yes. I see no mention of it. 

<p>
I have just <a href="https://s.ragavan.co/2019/08/1933-indiewebifying-my-website/">indiewebified my WP website</a> and am using <a href="https://github.com/org2blog/org2blog/issues/">org2blog</a> to post to it. I use the <a href="https://indieweb.org/Post_Kinds_Plugin">Post Kinds plugin</a> to set the kind as note / article / bookmark etc. 
</p>

<p>
There is a setting for the default kind. However, it seems to get 'activated' only if I login to WP and open the post and update it atleast once. All subsequent updates from Org mode don't change that.  Would be glad for advice on whether there is a way to specify the kind while exporting the post? 
</p>

**Comment by grettke** [comment]
Hi Shreyas. That plugin isn't supported. I want to know more about it.

When you say "default kind", is that metadata used by the Post Kinds plugin? If it is, what is its detailed name. If it isn't, where does that field come from?

With Org2Blog there is metadata that is updated each time you save your entry. For example as you add or remove tags. 

From what I can see while quickly skimming the plugin page, I'm _guessing_ that this plugin creates new [Taxonomies](https://wordpress.org/support/article/taxonomies/). Org2Blog only supports the default categories and tags taxonomies right now.

Tell me more about what you know about the plugin and think about my feedback.

**Comment by grettke** [comment]
Closing this issue because it doesn't seem to be related to an Org2Blog feature, is not active, and it isn't obvious how to move forward with it. If work can start again then this task will get get re-opened.

**Comment by shrysr** [comment]
Hi Grant,

I apologise for the lack of response, and agree with your course of action. To be honest - I've switched back to using ox-hugo, and am not using org2blog for now. However, I do have plans to get back to this discussion at some point in the future, as an Indieweb type site with webmentions is much easier to setup on WP than on hugo (which I've not done).

**Comment by grettke** [comment]
@shrysr Gotcha. Glad to hear you are blogging and look forward to whatever the future brings.
