### ISSUE TITLE
Support for custom fields/taxonomies

### ISSUE THREAD

**Issue by neonnoodle** [org2blog/org2blog#278]
On the custom WP setup I run, we have multiple custom fields and taxonomies for post metadata. I'd love to be able to write directly to these as I can with tags and categories.

**Comment by grettke** [comment]
I hear you. Like you said right now Org2Blog only supports categories and tags.

In the future I do want to switch over to supporting Taxonomies.

**Comment by grettke** [comment]
@neonnoodle Since you use them do you have any ideas, preferences, thoughts, or feedback on how Org2Blog might best integrate that functionality from a user experience perspective?

**Comment by grettke** [comment]
Just added this to FUTURE.org so it is on the books and closing it because it is not active. When work starts again this task get get re-opened.
