### ISSUE TITLE
Fails to install with use-package

### ISSUE THREAD

**Issue by ulloa** [org2blog/org2blog#280]
```
... many other configs
  (add-to-list
   'package-archives
   '("melpa" . "http://melpa.org/packages/") t)

.... many other configs
    (use-package org2blog
             :ensure t)
```

Error (use-package): Failed to install org2blog: http://melpa.org/packages/lv-20190716.1741.el: Not found
Error (use-package): Cannot load org2blog

emacs version 27.0.50. I feel like something was wrong with the MELPA recipe not sure. I haven't ever tried this package, but everything else is installed on my emacs using use-package with no problems.

**Comment by grettke** [comment]
Hi @ulloa . Thanks for trying it and letting me know. I'm going to take a look.

**Comment by grettke** [comment]
'hydra' depends on 'lv'. When I try installing `org2blog' with Use-Package it seems to load ok:

    Leaving directory ‘/Users/gcr/.emacs.d/elpa/lv-20190821.947’

    Compiling file /Users/gcr/.emacs.d/elpa/lv-20190821.947/lv.el at Mon Oct 14 07:21:21 2019
    Entering directory ‘/Users/gcr/.emacs.d/elpa/lv-20190821.947/’

Can you try installing 'lv' using the package UI and see if that works? If it does can you delete the package try installing org2blog again using use-package?

**Comment by grettke** [comment]
Thanks @ulloa . I've got issues due to load order I missed some stuff. Installing from use-package forced the issue to get revealed. I'll update my build docs too.

**Comment by grettke** [comment]
@ulloa I was looking at it some more. Are you still running into that problem?

**Comment by grettke** [comment]
I tried installing org2blog a few times using use-package and it installed lv correctly each time. 

How is it going for you now?

**Comment by ulloa** [comment]
It wouldn't work this morning either without installing lv (not sure if you had updated the repo or not). I installed lv using the list-packages menu and the org2blog installation worked fine from there. I don't install packages using the list-packages menu generally though. 

I wouldn't necessarily find a work around for my behalf considering I am only thinking of trying project out. Up to you.

**Comment by grettke** [comment]
I see. No I didn't make any changes to the org2blog-pkg.el. 

It is definitely worth figuring out why since you are probably not the only person to ever face this. The problem I ran into is that I can't reproduce it.

It sounds like you worked around this issue. Please close the ticket if you think we should stop digging into this.

**Comment by grettke** [comment]
Please feel free to open this again if you want to go further with it.
