### ISSUE TITLE
Default Tags Do Not Load From Org2Blog Profile in init.el

### ISSUE THREAD

**Issue by bradfonseca** [org2blog/org2blog#284]
Thank you for filing this bug report. To make it easier for you and easier for
us please answer these five short questions:

- What did you do?
Created a org2blog profile (if that's the correct word) in my `init.el` with `:default-tags` set:

![org2blog_setup_profile_init_file](https://user-images.githubusercontent.com/4379354/73983021-7717cf00-4903-11ea-9260-fe686d447dd6.png)

- What did you expect to happen
I expected the `#+TAGS: ` meta-data to be populated with my default tags, `org2blog` and `emacs`

- What happened instead?
They were left blank:
![org2blog_new_buffer_original_set-up](https://user-images.githubusercontent.com/4379354/73983145-bcd49780-4903-11ea-8d65-21c344255af3.png)

- Did you review issue tracker to see if this bug is already
  reported or resolved?
Yes, I did not see this issue reported yet.

- Did you review the README about how this feature works?
Yes. As well, this feature worked in org2blog 0.5, which is the last version I used.

**Comment by grettke** [comment]
Gotcha. I get the same behavior. I'm going to figure this out.

**Comment by grettke** [comment]
@bradfonseca Did the documentation or something else mention the `default-tags` property? Default tags aren't supported although I thought they were in there, they aren't.

**Comment by grettke** [comment]
That is a good feature. I will add it and keep you updated here.

**Comment by grettke** [comment]
@bradfonseca Just pushed the code with the default tags feature.

Here is what to add to your Org2Blog config:

    :default-tags ("taga" "tagb" "tagc")
    :default-tags-sub ("subtaga" "subtagb" "subtagc")

Let me know how it goes.

**Comment by grettke** [comment]
Closing this issue because it is not active and it was obvious how to move forward with it. It should be resolved now. If work needs to restart then this task will get get re-opened.
