### ISSUE TITLE
No space between listing number and caption when using the Plain Source Box Format

### ISSUE THREAD

**Issue by waveFrontSet** [org2blog/org2blog#285]
- What did you do?
`(setq org2blog/wp-use-sourcecode-shortcode nil)` and export an org document with source blocks to wordpress.
- What did you expect to happen
In particular, I expected a space between, say, "Listing 1." and the caption text of the first source block.
- What happened instead?
No space between them.
- Did you review issue tracker to see if this bug is already
  reported or resolved?
Yes.
- Did you review the README about how this feature works?
Yes.

### Example
To make this a little clearer, here's a simple example:
```org
#+caption: This is a caption
#+BEGIN_SRC python
print("Test.")
#+END_SRC
```
Using the Plain Source Box Format, this generates the following html when exporting to wordpress:
```html
<label class="org-src-name"><em><span class="listing-number">Listing 1.</span>This is a caption. </em></label>
```
Note that there is no space between the closing `span`-Tag and the word "This".

### Analysis

I suppose that the issue is that there is no space in between the two `%s` in the format string in the function `ox-wp-src-block-html`:
https://github.com/org2blog/org2blog/blob/58398120907504ff200adfd9b817f297142c9680/ox-wp.el#L168-L170

Note that using Syntax Highlighter Evolved works because a space is added after the variable `footnote` in the corresponding function `ox-wp-src-block-shortcode`:
https://github.com/org2blog/org2blog/blob/58398120907504ff200adfd9b817f297142c9680/ox-wp.el#L125-L127

**Comment by grettke** [comment]
Hi @waveFrontSet . Thank you for the thoughtful and detailed report an analysis.

Certainly looks like that code is resonsible.

I will make the fix this week.

**Comment by grettke** [comment]
@waveFrontSet Just committed the change in v1.1.3.

I added the space and tidied up the logic a little bit.

My todo list has an entry to update the screenshots.

Let me know if you run into any issues.

Please close the issue if it is resolved.

**Comment by waveFrontSet** [comment]
Looks great! Thanks for the blazingly fast fix!

**Comment by grettke** [comment]
@waveFrontSet You are welcome. Thanks and have a great day.
