### ISSUE TITLE
Suppress title "Listing..." from source block output?

### ISSUE THREAD

**Issue by higham** [org2blog/org2blog#286]
As a long-time org2blog user I noticed that in recent versions
#+begin_src
prints a "Listing ..." title before the source block.
This does not happen with Org export to other formats.
Is there any way to turn off this title and, if not, can an option to do so be provided?
At the moment I've resorted to hacking ox-wp.el, which is obviously not desirable.

**Comment by grettke** [comment]
Hi @higham Gotcha. That should have been configurable: sorry for the inconvenience this caused. I will add the feature then update this thread within the next 4 days.

**Comment by grettke** [comment]
@higham I removed that functionality because it didn't work. The changes are committed and if you use MELPA then it will be available pretty soon. If it looks good then please close the issue. Let me know how it goes.

**Comment by higham** [comment]
The change solves the problem.  Many thanks for your quick response!

**Comment by grettke** [comment]
@higham You are welcome. Have a good day and happy blogging!
