### ISSUE TITLE
DESCRIPTION (aka excerpt) is not working.

### ISSUE THREAD

**Issue by chenyukang** [org2blog/org2blog#288]
I updated to the latest version, 
DESCRIPTION (aka excerpt) is not working, the same with the old version.

I add:

```org
#+DESCRIPTION: Here should be excerpt part.
```

But it does not show in WP.

**Comment by grettke** [comment]
@chenyukang Gotcha. In light of the current world events I won't work on this as soon as I would like. However I understand what you are saying and I will take care of this eventually.

**Comment by nickmose8** [comment]
> @chenyukang Gotcha. In light of the current world events I won't work on this as soon as I would like. However I understand what you are saying and I will take care of this eventually.

Hey @grettke , thanks for reply!   
org2blog is an important package I daily used. Grateful for your contribution.
I will also try to solve it by myself, but currently I'm not familar with WP's API .

Take care and keep well!

**Comment by chenyukang** [comment]
Hey @grettke , thanks for reply!
org2blog is an important package I daily used. Grateful for your contribution.
I will also try to solve it by myself, but currently, I'm not familiar with WP's API .

Take care and keep well!

**Comment by grettke** [comment]
@chenyukang  Thanks for your patience here: I will be working on this ASAP.

**Comment by chenyukang** [comment]
@grettke 
I just made a fix for this, it's work for me now!
Please have a review.
The Travis Ci is broken, seems can not update Emacs in Travis CI.

**Comment by grettke** [comment]
@chenyukang That is excellent news.

Thank you for the code.

Right now I'm reading about on how WordPress uses `description` and `excerpt` in its API because when I look at how Org2Blog is using I am surprised that the former is set to `nil`. I will report back.

**Comment by grettke** [comment]
@chenyukang Just merged your change thank you very much for your time and effort.

For reference I did remove the change to `DESCRIPTION` because I'm going to address that in #299 as it takes a lot more changes.
