### ISSUE TITLE
Upload note for image no longer placed with post

### ISSUE THREAD

**Issue by higham** [org2blog/org2blog#290]
The documentation says that when an image is uploaded, org2blog

"Make a note in the Org2Blog entry so that it remembers that it
already uploaded the image file to your blog."

There has been a change in behaviour.  The upload note used to go
in the post entry but (in org2blog-20200317.2136 and probably other
recent versions) the note is now being put at the end of the Org
file.  I have multiple posts per file and narrow down to the post
in question when working on it.  The upload note is therefore
invisible.

Can the previous behaviour be reinstated?  It's more logical and
easier to work with.  Also, making changes outside a narrowed
region is not good practice.

**Comment by grettke** [comment]
Hi @higham 

First sorry for the inconvenience. That is definitely an unpleasant experience. It will get resolved soon.

The behavior your describe makes sense to me. I need to investigate why `widen` is being used during posting and figure out how to move forward. Then I will get back to you.

How you are using Org2Blog with multiple buffer-entries in a single file where you are simply narrowing to them: it surprises me! I don't know of it ever being used in that way before. As far as I knew people used subtree-entries to store multiple posts in one file. Once I know more I will add it to the documentation as an approach.

**Comment by higham** [comment]
> How you are using Org2Blog with multiple buffer-entries in a single file where you are simply narrowing to them: it surprises me!

Yes my "blog.org" looks like

* Post 1
* Post 2
...

I've got used to narrowing (and forget if org2blog works without it) since exporting more generally with the whole buffer active will export the whole buffer by default.  I often print a draft blog post by exporting to LaTeX to get a nicely formatted PDF file.

**Comment by grettke** [comment]
Thanks for explaining that.

Right now my attention is going to personal logistics tasks given world-events.

As soon as they are addressed I'm going to return to this task.

Be well.

**Comment by grettke** [comment]
@higham Thanks for your patience here: I will be working on this ASAP.

**Comment by grettke** [comment]
@higham Just committed the fix. My apologies for the delay implementing this.  At the time of writing this comment the world was still under quarantine from COVID-19 and it certainly affected a lot of people in a lot of ways! Please let me know how the fix works for you.

**Comment by higham** [comment]
Many thanks, Grant. What did you implement in the end?

**Comment by grettke** [comment]
After you explained this

> Can the previous behaviour be reinstated? It's more logical and
> easier to work with. Also, making changes outside a narrowed
> region is not good practice.

it made sense to me and that is the change that I made.

You are welcome and thanks for investing your time in this: it is feedback like yours that is critical to shaping Org2Blog into what it can and should be :).

**Comment by grettke** [comment]
For reference this is how Narrowing works with Org2Blog:

https://github.com/org2blog/org2blog#using-narrowing
