### ISSUE TITLE
I’m sorry I ran into a problem trying to load categories inside of ‘org2blog-user-login’

### ISSUE THREAD

**Issue by cryoguy** [org2blog/org2blog#292]
I am getting following error when I try to log into one of blog site. It was working fine .  It was also reported[ elsewhere](https://sachachua.com/blog/2014/02/excuses-guide-blogging-pdf-epub-mobi-free-also-notes-publishing/#comment-658929). Any thoughts?

```
(error Error during request: 404)
Org2Blog Runtime: Org2Blog 1.1.8, Emacs 26.3, Org Mode 9.3.6, MetaWeblog 1.1.1, XML-RPC 1.6.12
Error (org2blog/wp): I’m sorry I ran into a problem trying to load categories inside of ‘org2blog-user-login’.
Error (org2blog/wp): 2020-04-14T16:30:06-07:00
Please report that along with the following details:
(error Error during request: 404)
Org2Blog Runtime: Org2Blog 1.1.8, Emacs 26.3, Org Mode 9.3.6, MetaWeblog 1.1.1, XML-RPC 1.6.12
```

**Comment by grettke** [comment]
Hi @cryoguy . Glad you reached out I know it can be frustrating getting errors like that. Here is how I am thinking we can start looking at this from less detailed to more details:

Are you able to access your blog using the computer you are working from using a web browser?

Are you able to log into the admin section of your blog on the computer you are working from using the same username and password that you are using with Org2Blog?

When you hit `[Login]` does it succeed or are there error messages? As you explained, there is a 404 error. The [HTTP 404](https://en.wikipedia.org/wiki/HTTP_404) error usually means that the computer can't reach the website. Or that the website isn't answering when the web browser or Emacs calls it. The first two questions will help with this.

Enable reporting via `[Reporting On]`. Then read the documentation for `org2blog-user-report` by striking `Control h` then striking `f` then `enter` then typing in `org2blog-user-report` and striking `enter`. That will present you with great detail about how to see the error messages available. Specifically you can look in the buffers `func-call` and `*URL-DEBUG*` to get more details. Feel free to share details here about connection and 404 or anything else that seems useful. However **first remove your username and password** and anything else you want to keep a secret. The buffers display those values in clear text.

**Comment by cryoguy** [comment]
I can access the site and log in with the credentials org2blog using without any issue.  Could these a problem with xmlrpc package?  This is what I got when I reinstall org2blog with the following config:

`(use-package org2blog
:ensure t)`


Compiling file /home/tan/.emacs.d/elpa/org2blog-20200317.2136/ox-wp.el at Thu Apr 16 22:16:24 2020

Compiling no file at Thu Apr 16 22:16:25 2020
Error (bytecomp): Cannot open load file: Not a directory, xml-rpc
Warning (bytecomp): defsubst ‘xml-rpc-value-intp’ was used before it was defined\\
Warning (bytecomp): defsubst ‘xml-rpc-value-doublep’ was used before it was defined`\\
Warning (bytecomp): defsubst ‘xml-rpc-value-stringp’ was used before it was defined
Warning (bytecomp): defsubst ‘xml-rpc-value-structp’ was used before it was defined
Warning (bytecomp): defsubst ‘xml-rpc-value-arrayp’ was used before it was defined
Warning (bytecomp): defsubst ‘xml-rpc-value-vectorp’ was used before it was defined
Warning (bytecomp): ‘string-as-unibyte’ is an obsolete function (as of 26.1); use ‘encode-coding-string’.
Warning (bytecomp): assignment to free variable ‘org2blog/wp-blog-alist’
Warning (bytecomp): ‘org-plain-link-re’ is an obsolete variable (as of Org 9.3); use ‘org-link-plain-re’ instead.
Warning (bytecomp): ‘org-get-tags-at’ is an obsolete function (as of Org 9.2); use ‘org-get-tags’ instead.


I do say  "xml-rpc-20181002.1353" with the following files "xml-rpc-autoloads.el  xml-rpc.el  xml-rpc.elc  xml-rpc-pkg.el".

and I got the following when I log in from org2blog:
`Error (org2blog/wp): I’m sorry I ran into a problem trying to load categories inside of ‘org2blog-user-login’.
Error (org2blog/wp): 2020-04-16T22:41:20-07:00
Please report that along with the following details:
(wrong-type-argument listp (nil . URL/HTTP Error: 200))
Org2Blog Runtime: Org2Blog 1.1.8, Emacs 26.3, Org Mode 9.3.6, MetaWeblog 1.1.1, XML-RPC 1.6.12
`

**Comment by cryoguy** [comment]
After numerous failed tries, I installed org2blog with package-install, and it logged in fine this morning.   I wish I know the real cause of the issue.   

Org2blog is a beautiful package and I have been using it for years for one of [my blog](tech.memoryimprintstudio.com).  Thanks for your help and your work!

**Comment by grettke** [comment]
@cryoguy Saw your post when it came through and was #1 very glad to see that things are working as expected and #2 very appreciated that you shared your update. It always helps grow the answer base and that brings even more value to the ticket system. I hope you have a great day. Happy blogging!
