### ISSUE TITLE
Using WP shortcodes

### ISSUE THREAD

**Issue by toddfoster** [org2blog/org2blog#293]
Is there a clean/canonical way to use wordpress shortcodes in my org2blog entries? (I may be betraying some combination of ignorance of org2blog and of WordPress itself -- webdev is not my main gig, but I'm trying to learn enough to accomplish the tasks before me.)

I. What I did:
I use `[embed]` to include audio files stored on S3 instead of filling up my web server's media library. This works fine for me when editing through the WP GUI. So I tried various ways of including those in an org2blog post:

```
Testing embeds:

=[embed]https://s3.amazonaws.com/cdn.boidem.org/2020/psalms/Ps11921-Tav.mp3[/embed]=

[embed]https://s3.amazonaws.com/cdn.boidem.org/2020/psalms/Ps11921-Tav.mp3[/embed]

~[embed]https://s3.amazonaws.com/cdn.boidem.org/2020/psalms/Ps11921-Tav.mp3[/embed]~

[[https://s3.amazonaws.com/cdn.boidem.org/2020/psalms/Ps11921-Tav.mp3]]
```
II. Expectations
Ideally, I would like to be able to use wordpress shortcodes and just get verbatim output in my Wordpress editor: no markup, no `<code>` or `<p>` or anything. Then I expect Wordpress to process the shortcodes and provide the output I expect on Wordpress.

I'm not even stuck on shortcodes: I'd just like a quick/simple/clean way to embed audio file players in my site via org2blog.

III. What happened instead
When entering that code in the WP editor, I get an audio player widget. Indeed, the first and third attempts in the test above yielded that widget -- surrounded by `<p> <code>` tags which created extras space and a little grey "shadow" beneath. So the embed works, but it's not as "clean" as I would like (no extra whitespace or other artifacts in the html output). [You can see what I'm talking about.](https://www.stthomasglassboro.org/test-embed/)

IV. I searched the doc's for "shortcode," skimmed through the source of the "wordpress to org2blog converter" to see if I could notice anything, and searched the issue tracker. I also checked the FUTURE doc. 

This is hardly a bug: just me seeking the right way to use this tool. org2blog has drastically sped up my work flow as my community's website has become much more central to our internal communications since the pandemic lockdown began. Thank you!

**Comment by grettke** [comment]
Hi @toddfoster Thank you for the detailed and thoughtful issue, and also answering the questions: it is greatly appreciated. I have a couple ideas for you how to move forward.

The first thing to try is to make sure that Shortcodes are enabled like this:

`(setq org2blog/wp-use-sourcecode-shortcode t)`

The next time you `[Save Post Draft]` you should be able to go to the editor on WordPress and see the shortcode exactly as you wrote it in Org2Blog. Before you run that I'm curious to know the current of value of that variable you can check it by typing `Control-h` `v` `org2blog/wp-use-sourcecode-shortcode` then hit `enter`. You should see a buffer pop up with a message like this `Its value is t` (or nil). If it is `nil` then performing this first step will make shortcodes work

I found the documentation to be lacking in regards to this Shortcode configuration so I will add to it later.

I'm pretty sure that will work but if it doesn't then here is an immediate workaround:

Whatever content you put inside an HTML export block will show up verbatim in your post. It might look like this:

    #+begin_export html
    [embed]https://s3.amazonaws.com/cdn.boidem.org/2020/psalms/Ps11921-Tav.mp3[/embed]
    #+end_export

Then when you go into the WordPress editor it should exactly the same.

Whatever happens please let me know.

**Comment by toddfoster** [comment]
@grettke --

Thank you for looking at this with me!

My default value of wp-use-sourcecode-shortcode is indeed nil:
```
org2blog/wp-use-sourcecode-shortcode is a variable defined in ‘org2blog.el’.
Its value is nil

Documentation:
Non-nil means convert <pre> tags to WP sourcecode blocks.

The blog specific property is: :wp-code

You can customize this variable.
```

So the default result in the wordpress editor is this:
```
<p> Testing embeds: </p>

<p> <code>[embed]https://s3.amazonaws.com/cdn.boidem.org/2020/psalms/Ps11921-Tav.mp3[/embed]</code> </p>

<p> [embed]<a href="https://s3.amazonaws.com/cdn.boidem.org/2020/psalms/Ps11921-Tav.mp3">https://s3.amazonaws.com/cdn.boidem.org/2020/psalms/Ps11921-Tav.mp3</a>[/embed] </p>

<p> <code>[embed]https://s3.amazonaws.com/cdn.boidem.org/2020/psalms/Ps11921-Tav.mp3[/embed]</code> </p>

<p> <a href="https://s3.amazonaws.com/cdn.boidem.org/2020/psalms/Ps11921-Tav.mp3">https://s3.amazonaws.com/cdn.boidem.org/2020/psalms/Ps11921-Tav.mp3</a> </p>
```

Setting the property...
```
org2blog/wp-use-sourcecode-shortcode is a variable defined in ‘org2blog.el’.
Its value is t
Original value was nil
```
...seems to yield the same exact output.

**HOWEVER!**

I'm re-thinking my original question. In all three lines with shortcodes, the shortcodes come through to the WP editor. That doesn't seem to be a problem. The problem is actually the url. When the URL is in a code or verbatim block, it comes through verbatim. When it's not hidden in one of those blocks, it gets translate as an `<a href>` tag. And the [embed] shortcode seems to want a raw URL, not a `<a>` tag. Likewise, a raw url without any tags at all by default receives an embedded player (added via WP editor to the end of the example post above).

I don't know if it's orgmode or org2blog that's translating my url into an `<a href>`. But I think that's what I'm looking for: a "raw" URL so that WP can translate it instead of emacs/orgmode/org2blog.

As you note, providing the URL within a `#+BEGIN_SRC html` block does indeed give me the output I want: thank you. I wonder if there is a cleaner way to pass a raw URL.

**Comment by grettke** [comment]
@toddfoster My apologies for the delay covering this. At the time of writing this comment the world was still under quarantine from COVID-19 and it certainly affected a lot of people in a lot of ways! Here is what I think would work for you: add this code somewhere in your configuration file (and run it too):

    (require 'org)
    (org-link-set-parameters
     "toddfoster-embed"
     :export #'toddfoster-embed-export)
    (defun toddfoster-embed-export (link description format)
      "Demo of un-marked URLs for the embed shortcode."
      (format "[embed]%s[/embed]" link))

When you write your blog entry input your embedded media URLs like this:

    [[toddfoster-embed:https://s3.amazonaws.com/cdn.boidem.org/2020/psalms/Ps11921-Tav.mp3]]

You should get a rendering that looks like this:

<img width="660" alt="Screenshot 2020-06-11 13 12 36" src="https://user-images.githubusercontent.com/2521647/84424155-49aa9d00-abe5-11ea-8809-c05255c16f02.png">

With code that looks like this:

    <p> [embed]https://s3.amazonaws.com/cdn.boidem.org/2020/psalms/Ps11921-Tav.mp3[/embed] </p>

Please let me know how this works for you.

**Comment by grettke** [comment]
@toddfoster Here is a simpler one:

    @@html:[embed]https://s3.amazonaws.com/cdn.boidem.org/2020/psalms/Ps11921-Tav.mp3[/embed]@@

**Comment by toddfoster** [comment]
@grettke : Thank you for your time on this. The pandemic has disrupted very many things: free assistance on an open source project can wait!

In the meantime, you inspired me with the parameter about using shortcodes. I scratched my own itch by writing a plugin for WordPress (using the "Code Snippets" plugin so it gets backed up with the rest of the site db). In this way I avoid the question of having my url's hijacked.

However, you ``@@html:..@@`` solution is beautiful. And I'm guessing this is an org built-in that I might use again in the future!

So I can get the same result with:

```
@@html:[embed]https://s3.amazonaws.com/cdn.boidem.org/2020/psalms/Ps11920-Resh.mp3[/embed]@@
```

or with

```
[embedcdn2020 psalms/Ps11920-Resh.mp3]
```

Thanks again for your help with this!

**Comment by grettke** [comment]
@toddfoster So glad to hear how you moved forward. WordPress is a real treat to use and develop for and it sounds like it was that way for you. Same goes to me.

You are right, those HTML quoting tags tell the Org html exporter to _not_ do its job just right then.
