### ISSUE TITLE
comments with disqus?

### ISSUE THREAD

**Issue by AtomicNess123** [org2blog/org2blog#309]
quick q: Does this package allow for comments like Disqus?

**Comment by grettke** [comment]
@AtomicNess123 Although I am not familiar with Disqus integration I think it does and here is what I mean:

Disqus is a commenting platform. It integrates to your blog using a plugin. You make a post and the post is stored on your server. People make comments and they are stored on the Disqus servers.

The workflow with Org2Blog is the same:

- You write a post in Org mode. It is a file on your computer.
- You publish it to your blog. It is stored in WordPress.
- People comment it. Comments are stored in Disqus for that post.

The thing that ties together the file, the post, and the comments is that the post has a single `identifier (ID)`: the unique number that makes it different from every other post. The file has that ID, the post has that ID, the comments have that ID to associate them with the post. 

That is why I believe that you can use Org2Blog with Disqus comments.

What do you think?

**Comment by AtomicNess123** [comment]
I think you are totally right. My knowledge is so constrained, but it makes sense. I will try it, thanks.

**Comment by grettke** [comment]
@AtomicNess123 Sounds good. Let me know how it goes.
