### ISSUE TITLE
#+begin_export wp

### ISSUE THREAD

**Issue by sachac** [org2blog/org2blog#311]
Thank you for filling out this feature request (FR). Please perform every step and answer every question to the best of your ability. That will make it easier for you and more accessible for us to address the feature request with the highest level of quality in the shortest amount of time.

### Description

It would be nice for #+begin_export wp to be exported as part of the output, which would allow things like org-special-blocks-extras to work with org2blog export.

### Prerequisites

* [X] Did you study the [README](https://github.com/org2blog/org2blog/blob/master/README.org) and learn how the existing Org2Blog features work?
* [X] Did you review the issue tracker to see if this FR already
exists or is resolved?
* [X] Have you reviewed the [FUTURE](https://github.com/org2blog/org2blog/blob/master/FUTURE.org) file to see if the FR already exists?

### Type of FR

Please try to limit your FR to one type, submit multiple FRs if needed.

Please check the type of feature you are requesting:
- [ ] Brand New Feature
- [X] Change Existing Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Describe the solution you'd like

We can modify the backend to include both wp and html blocks so that org-special-blocks-extra would work and so that people can have a #+begin_export wp that is included only when publishing to org2blog.

### Describe alternatives you've considered

I considered just supporting wp blocks, but that changes the current functionality.

### Screenshots

None

### Additional context

#+begin_src emacs-lisp
(with-temp-buffer
  (insert "* Hello
#+begin_export wp
<div class=\"test\">This should appear in WP export.</div>
#+end_export
Text in between
#+begin_export html
<div class=\"test\">This should appear in WP and HTML export</div>
#+end_export
")
  (org-mode)
  (goto-char (point-min))
  (org-export-as 'wp t nil t))
#+end_src

#+RESULTS:
:results:
<div class="test">This should appear in WP export.</div>
<p> Text in between </p>

<div class="test">This should appear in WP and HTML export</div>
:end:

**Comment by grettke** [comment]
Closed in #312

**Comment by grettke** [comment]
For the sake of the record, I just updated the section "Raw HTML Creation" in the README with the new Org2Blog behavior.

From now on, people should use the ~wp~ export block instead of ~html~. It is simple: people rarely exported both to WordPress /and/ HTML. However, if they do, it will still work correctly.
