### ISSUE TITLE
Nothing but appreciation

### ISSUE THREAD

**Issue by paniash** [org2blog/org2blog#314]
Hi! Thanks a lot for this wonderful project. Just wanted to appreciate the good work. :-)

Also, was curious about the monospace font used in the images in the README. Thanks!

**Comment by grettke** [comment]
Thank you for the kind words.

The font is [Hack](https://sourcefoundry.org/hack/).

If you are interested in my top five font choices and how I narrowed it down to one, then [here is now](https://www.wisdomandwonder.com/text/12298/choosing-a-monospace-font-2019-march). 

There were very slight differences between my Top 2, but they made a huge difference.

**Comment by grettke** [comment]
@paniash What is your favorite font?

**Comment by paniash** [comment]
@grettke Thanks a lot! Your site looks really clean btw. :-)

I used to be on inconsolata but about a week back, switched to DejaVu Sans Mono and have never looked back. I slightly prefer it over Hack.
