### ISSUE TITLE
Underline in org mode does not appear in preview

### ISSUE THREAD

**Issue by LukeFernandes** [org2blog/org2blog#328]
Sorry if missing something obvious, but the use of _xxx_ markup to signify underline does not carry over when org2blog saves my blog to Wordpress. The desired functionality is that text so marked up should appear to be underlined in Wordpress.

**Comment by grettke** [comment]
Thank you @LukeFernandes for letting me know. It _used_ to work, but something changed.

Here is the Org:

```
_I should be underlined but I am not._
```

here is the generated HTML:
```
<span class="underline">Underlined via export</span>.
```

I believe that it needs to be a `<u>` so I will look into it.

**Comment by grettke** [comment]
That HTML gets generated using `org-html-text-markup-alist` in `ox-html.el` for future reference.

**Comment by LukeFernandes** [comment]
Thanks for getting back on this so quickly, I look forward to news of a fix.
Thanks
Luke

**Comment by grettke** [comment]
The Org HTML exporter uses CSS `underline` class. But we're not using that for now and stick with plain HTML.

With the change this:

```
Not underlined.

_Underlined with updated ox-wp exporter_.

@@html:<u>@@Manually underlined with escaped html@@html:</u>@@.

[[https://reddit.com][Example of a link to see how it is underlined]].
```

becomes this

<img width="396" alt="Screen Shot 2022-10-30 at 2 11 35 PM" src="https://user-images.githubusercontent.com/2521647/198897108-b967daa1-8847-48c7-a134-d53497a3b522.png">


and

```
<p> Not underlined. </p>

<p> <u>Underlined with updated ox-wp exporter</u>. </p>

<p> <u>Manually underlined with escaped html</u>. </p>

<p> <a href="https://reddit.com">Example of a link to see how it is underlined</a>. </p>
```

When you have a chance please get an update and try it out and report back.

It is in commit `a77a549de75e1f1c8c806b30f7fd2dd0b2ea8593`.

I'll do a new release once we've tested it out for a while.

**Comment by LukeFernandes** [comment]
Hi, thanks!
I replaced the old ox-wp.el with the new one, and used byte-recompile-directory to compile the package. I got lots of warnings and the following error:

ox-wp.el: Error: Invalid read syntax: "#", 567, 162

**Comment by grettke** [comment]
This looks like a _it worked on my computer_ because I get:

```
Compiling file /Users/grant/src/org2blog/ox-wp.el at Mon Oct 31 21:27:22 2022

In ox-wp-src-block-shortcode:
ox-wp.el:111:8: Warning: docstring wider than 80 characters

Compiling internal form(s) at Mon Oct 31 21:27:50 2022
```

Can you please share the results of `org2blog-version-info`?

What package manager do you use (or how) do you install the package?

**Comment by LukeFernandes** [comment]
Thanks. Version info is as follows: Org2Blog Runtime: Org2Blog 1.1.15, Emacs 29.0.50, Org Mode 9.5.5, MetaWeblog 1.1.15, XML-RPC 1.6.15, HTMLize 1.57

I use MELPA and install it from list-packages.

**Comment by LukeFernandes** [comment]
[ox-wp (copy).el.txt](https://github.com/org2blog/org2blog/files/9944666/ox-wp.copy.el.txt)

Renamed to txt so I could upload!

**Comment by grettke** [comment]
Thanks Luke.

I just double-checked the file from MELPA and it is the version I expect. So it _should_ work right on your computer

My mind is stuck at "It works on my computer.", so I need to think different here.

Are you able to delete the `org2blog` folder in your ELPA folder and install it again?

When the package install, if there are compilation errors, they will show up at installation time. If they do, please paste them here. If they don't then please try it out and report back.

We will figure this out.

**Comment by LukeFernandes** [comment]
Thanks. I've deleted and reinstalled - no errors. I download the ox-wp.el file you've modified and place it in my org2blog folder instead of the old version. Then I byte recompile. I've attached the warning and error list...
[builderrors.txt](https://github.com/org2blog/org2blog/files/9946502/builderrors.txt)

**Comment by LukeFernandes** [comment]
Many apologies. I just realised I was saving the html file enclosing ox-wp.el like an idiot. A cursory look at the file could have helped me. Sorry to have wasted your time.

Anyway, the underline is working with the new version of ox-wp.el!

**Comment by grettke** [comment]
Excellent. Have fun blogging.
