### ISSUE TITLE
Support for subpages

### ISSUE THREAD

**Issue by benthamite** [org2blog/org2blog#334]
### Description

Support for [subpages](https://wordpress.org/support/article/pages/#creating-a-subpage).

### Prerequisites

* [X] Did you study the [README](https://github.com/org2blog/org2blog/blob/master/README.org) and learn how the existing Org2Blog features work?
* [X] Did you review the issue tracker to see if this FR already
exists or is resolved?
* [X] Have you reviewed the [FUTURE](https://github.com/org2blog/org2blog/blob/master/FUTURE.org) file to see if the FR already exists?

### Good Documentation

Are you willing to write new or refine the existing documentation as this feature request moves through its lifecycle?

Please choose one of the following:

- [X] Yes.
- [ ] No. Please provide an explanation why.

### Type of FR

Please check the type of feature you are requesting:

- [X] Brand New Feature
- [ ] Change Existing Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Describe the solution you'd like

My blog relies extensively on subpages. Presumably the same is true for at least a few other users of this package. Currently, updating a subpage via org2blog moves it to the base level, requiring the user to log in to WordPress and placing it again under the parent page, which is frustrating for those of us looking for an Emacs-based workflow.

**Comment by grettke** [comment]
Hi @benthamite . I hear you. Does the [Parent Page](https://github.com/org2blog/org2blog#parent-pages) do what you would like it to?

**Comment by benthamite** [comment]
Oh, I completely missed this. (I searched for 'subpages' but not for 'sub pages'.) It does exactly what I need. Thank you.

**Comment by grettke** [comment]
Excellent. Happy Blogging!
