### ISSUE TITLE
Unknown 'nil' backend: Aborting Export on Save Draft

### ISSUE THREAD

**Issue by teledyn** [org2blog/org2blog#337]
### Description
Saving a new buffer fails showing message "Unknown 'nil' backend: Aborting Export"

### Prerequisites

* [x] Did you study the [README](https://github.com/org2blog/org2blog/blob/master/README.org) to learn how the feature you are reporting a bug is expected to work?
* [x] Did you go through the [When Things Go Wrong](https://github.com/org2blog/org2blog#when-things-go-wrong-or-could-go-even-better) process? It covers the steps to review many possibilies
* [x] Did you review the issue tracker to see if this bug is already
reported or resolved?
* [x] Did you consider that what you are describing may be a feature request? If you answered yes, review both the issue tracker and the [FUTURE](https://github.com/org2blog/org2blog/blob/master/FUTURE.org)  file to see if the feature request already exists.

### Environment

It did work, quite well too, but I must confess not using Org2Blog for several months, returning to it after several changes that may have impacted this code:

- My wordpress installation was adapted to HTTP/2, which can impact PHP. My login appears to work fine, and the wordpress editor configuration has not changed although I am certain the Wordpress version has been updated.
- In Emacs, I have upgraded to the git clone for OrgMode 9.7.1 as this fixed many problems I had with publishing footnotes to HTML. For some reason, installing from GNU ELPA would flood my system with warnings about GNU replacing ORG ELPA on every load.

My blog list is irrelevant. It worked fine, nothing about the network has changed, and it is an internal, non-public blog on the same ethernet LAN.  But what might help is the backtrace on error and I will include that

### org2blog-version-info`

```
Org2Blog Runtime: Org2Blog 1.1.16, Emacs 29.3, Org Mode 9.8-pre,
  MetaWeblog 1.1.16, XML-RPC 1.6.17, HTMLize 1.57
```

I did the `org2blog-user-report` process: it replied
```
Disabling detailed reporting about *everything* that I am doing. Enjoy the silence.
```
I haven't heard from it since! that was about 35 minutes ago. You mention log files, where would these be?

? If you did then please paste in the log files here [+yes+/No]:

```
Paste the logs here.
```

### Server

- What is the URL of your blog? private
- Do you have a web browser to use for testing? several
- Can you reach that URL using that browser? all of them
- Can you log into your blog using that browser? all of them
- Can you create or edit a post using that browser? all of them

### Hardware Issues

I- Have you tried rebooting your computer? n/a
- Have you tried rebooting your router? n/a
- Have you tried rebooting your server? n/a

### Steps to Reproduce

1. [First Step] M-x org2blog-user-interface
2. [Second step] New Buffer
3. [Third step] type anything, no nuts
4. [Fourth step] C-c M-p g j

### Expected behavior

[What you expected to happen] buffer is saved as draft on the Wordpress server

### Actual behavior

[What actually happened] `Unknown 'nil' backend: Aborting Export`

### Additional context
```
Debugger entered--Lisp error: (error "Unknown \"nil\" backend: Aborting export")
  error("Unknown \"%s\" backend: Aborting export" nil)
  org-export-barf-if-invalid-backend(nil)
  org-export-as(wp nil nil t (:section-numbers nil :with-priority nil :with-sub-superscript nil :with-toc nil :with-tags nil :with-todo-keywords nil :wp-keep-new-lines t :wp-latex t :wp-shortcode nil :tags-as-categories nil :wp-shortcode-langs-map nil))
  org-export-to-buffer(wp "*Org WordPress Export*" nil nil nil t (:section-numbers nil :with-priority nil :with-sub-superscript nil :with-toc nil :with-tags nil :with-todo-keywords nil :wp-keep-new-lines t :wp-latex t :wp-shortcode nil :tags-as-categories nil :wp-shortcode-langs-map nil) #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_0>)
  ox-wp-export-as-wordpress(nil nil (:section-numbers nil :with-priority nil :with-sub-superscript nil :with-toc nil :with-tags nil :with-todo-keywords nil :wp-keep-new-lines t :wp-latex t :wp-shortcode nil :tags-as-categories nil :wp-shortcode-langs-map nil))
  ox-wp-export-as-string(nil nil (:section-numbers nil :with-priority nil :with-sub-superscript nil :with-toc nil :with-tags nil :with-todo-keywords nil :wp-keep-new-lines t :wp-latex t :wp-shortcode nil :tags-as-categories nil :wp-shortcode-langs-map nil))
  org2blog--export-as-html(nil (:section-numbers nil :with-priority nil :with-sub-superscript nil :with-toc nil :with-tags nil :with-todo-keywords nil :wp-keep-new-lines t :wp-latex t :wp-shortcode nil :tags-as-categories nil :wp-shortcode-langs-map nil))
  org2blog--export-as-post(nil)
  org2blog-entry-save(buffer post nil)
  org2blog-buffer-post-save(nil)
  funcall-interactively(org2blog-buffer-post-save nil)
  hydra--call-interactively-remap-maybe(org2blog-buffer-post-save)
  org2blog--hydra-main/org2blog-buffer-post-save-and-exit()
  funcall-interactively(org2blog--hydra-main/org2blog-buffer-post-save-and-exit)
  command-execute(org2blog--hydra-main/org2blog-buffer-post-save-and-exit)
```

ox-wp.el is in the Org2Blog files and compiles with only a warning.

**Comment by teledyn** [comment]
While it is nice to be back on trying to solve this (after a series of sysadmin fires) I sadly must report that 5 months later this situation remains. In another post where this same error occurs when exporting to Markdown, the solution was to add `(require \`ox-md)` to the init, and the closest parallel I could think of would be `ox-wp`, but adding that did not correct the error.  Are there perhaps other ox- packages that are either needed installed or needing explicit require statements?

**Comment by teledyn** [comment]
And his is a final fix that I should have tried first: I fetched the `ox-wp.el` fresh from here (because it was a different size from the one I had) and recompiled, reloaded, and the issue has gone away!

**Comment by grettke** [comment]
@teledyn Glad to hear and thank you for reporting in what you found.
