### ISSUE TITLE
Can't upload posts with large images

### ISSUE THREAD

**Issue by maroony** [org2blog/org2blog#80]
Your plugin works very fine right now. But every time I want to post an article which includes an large image file ( > 1,5 mb), I get the error

No methodResponse found.

I use this code:  [[./img/test.jpg]] with org2blog/wp-post-subtree

Emacs: 23.3, Org: 7.8.02

**Comment by grettke** [comment]
Just read those posts and it doesn't seem to be an issue anymore. I just tested posting a 1.9M file and it worked correctly so I'm closing this noting my configuration today:

```ECM Information As Of: 2017-07-25T09-55-52
Org-Version: 9.0.9
Org-Git-Version:
         release_9.0.9-678-g0623c1
Emacs-Version: GNU Emacs 25.2.1 (x86_64-apple-darwin15.6.0, Carbon Version 157 AppKit 1404.47)
 of 2017-07-23
org2blog/wp-version is a variable defined in ‘org2blog.el’.
Its value is "1.0.0"
```
metaweblog is also at version 1.

**Comment by TheodoreEhrenborg** [comment]
I had a similar problem, with this error message.

> Error (org2blog/wp): I’m sorry I ran into a problem inside of ‘org2blog--upload-files-replace-urls’.
> Error (org2blog/wp): 2020-07-22T21:12:01-04:00
> Please report that along with the following details:
> (error No methodResponse found)
> Org2Blog Runtime: Org2Blog 1.1.10, Emacs 26.3, Org Mode 9.1.9, MetaWeblog 1.1.1, XML-RPC 1.6.12

I discovered that Org2Blog had uploaded the image, but WordPress had rescaled the image, so it was called image-scaled.jpg. 

I fixed the problem by adding this at the end of my org file:

`# image.jpg http://website.com/wp-content/uploads/2020/07/image-scaled.jpg`

**Comment by grettke** [comment]
@TheodoreEhrenborg Good to know. Thanks for sharing that!
