### ISSUE TITLE
Wordpress Template

### ISSUE THREAD

**Issue by titaniumbones** [org2blog/org2blog#83]
Any chance of defining a new variable
# +TEMPLATE:

Which would allow users to choose a wordpress template (maybe w/ completion, as in tags & categories) for a post? The use case may not be all that compelling, but it's significant for me -- I'm writing a bunch of posts that are meant to be visible only to logged in users, and I'm using templates to control this behaviour.    Not sure how hard it would be to make this work in the wp api.  

thanks again.
m

**Comment by grettke** [comment]
@titaniumbones Based on your commits this month it looks like you have switched to Hugo and Hugo is really nice. It has also been 3 years, 1 month, 26 days so I think that it is OK to close this ticket.
