### ISSUE TITLE
#+STYLE: lines getting stripped on upload to Wordpress

### ISSUE THREAD

**Issue by GiovanniMoretti** [org2blog/org2blog#99]
I'm want to create a page theat has two side-by-side images and have copied this fragment from the orgmode page on image handling and added the "width:45%":

```
#+STYLE: <style type="text/css">
#+STYLE:<!--/*--><![CDATA[/*><!--*/
#+STYLE: div.figure { float:left; width:45%; }
#+STYLE: /*]]>*/-->
#+STYLE: </style>
```

and then adding a pair of images:

```
#+attr_html: style="display:inline; margin:10; width:70%;"
#+caption: *CW Trainer, sending randomly generated callsigns*
[[file:CW-Trainer-Random.png]]
#+attr_html: style="display:inline; margin:10; width:70%;"
#+caption: *CW Trainer, selecting the characters to practise*
[[file:CW-Trainer-Settings.png]]

#+html: <p style="clear:both">
And the the text continues. 
```

This works happily when directly exporting to an HTML page, but when I use org2blog to push the page to my Wordpress site, none of the #+STYLE lines end up in the page's HTML, so the images end up one above the other, not side by side.

I've looked through org2blog.el but I can't see any lines that would filter the #+STYLE lines.

I'm a bit puzzled as to what code is removing these lines and what to do about it. Some pointers would be appreciated.

Thanks
Giovanni

**Comment by grettke** [comment]
In ox-wp.el, `org-wp-export-as-wordpress` delegates work to `org-export-to-buffer`

`org-export-to-buffer` can take eight arguments. The sixth argument is `BODY-ONLY`. Its behavior is documented in `org-export-as` stating that

> When optional argument BODY-ONLY is non-nil, only return body code, without surrounding template.

This is why only the body is exported here.

**Comment by titaniumbones** [comment]
@GiovanniMoretti , probably you should add custom CSS to your wordpress theme instead!
